using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;
using Xunit.Abstractions;
using Facet.Generators;
using VerifyXunit;
using VerifyTests;
using static VerifyXunit.Verifier;

namespace Facet.UnitTests.SourceGeneration;

/// <summary>
/// Tests for the basic Facet generator using Verify.SourceGenerators for snapshot testing.
/// These tests verify that the source generator produces correct, compilable code.
/// </summary>
public class FacetGeneratorTests
{
    private readonly ITestOutputHelper _output;

    public FacetGeneratorTests(ITestOutputHelper output)
    {
        _output = output;
    }

    [Fact]
    public Task FacetGenerator_WithBasicEntity_GeneratesExpectedDto()
    {
        // Arrange
        var source = @"
            using Facet;
            
            public class User
            {
                public int Id { get; set; }
                public string FirstName { get; set; }
                public string LastName { get; set; }
                public string Email { get; set; }
            }

            [Facet(typeof(User))]
            public partial class UserDto;
        ";

        var compilation = CreateCompilation(source);
        var generator = new FacetGenerator();

        // Debug: Check if compilation has errors
        var diagnostics = compilation.GetDiagnostics();
        foreach (var diagnostic in diagnostics)
        {
            _output.WriteLine($"Compilation diagnostic: {diagnostic}");
        }

        // Act
        var driver = CSharpGeneratorDriver.Create(generator)
            .RunGenerators(compilation);

        // Debug: Check the generator results
        var result = driver.GetRunResult();
        _output.WriteLine($"Generated {result.Results.Length} results");
        foreach (var generatedResult in result.Results)
        {
            _output.WriteLine($"Generator: {generatedResult.Generator.GetType().Name}");
            _output.WriteLine($"Generated sources: {generatedResult.GeneratedSources.Length}");
            _output.WriteLine($"Diagnostics: {generatedResult.Diagnostics.Length}");
            foreach (var diagnostic in generatedResult.Diagnostics)
            {
                _output.WriteLine($"  Generator diagnostic: {diagnostic}");
            }
        }

        // Assert - Extract and verify the generated source content
        var runResult = driver.GetRunResult();
        var generatedSources = SourceGeneratorTestHelpers.ExtractGeneratedSources(runResult);

        return Verify(generatedSources)
            .UseDirectory("__snapshots__")
            .UseFileName("BasicEntity")
            .ScrubLines(line => line.StartsWith("// <auto-generated"));
    }

    [Fact]
    public Task FacetGenerator_WithExcludedProperties_GeneratesCorrectDto()
    {
        // Arrange
        var source = @"
            using Facet;
            
            public class User
            {
                public int Id { get; set; }
                public string FirstName { get; set; }
                public string LastName { get; set; }
                public string Email { get; set; }
                public string Password { get; set; }
                public DateTime CreatedAt { get; set; }
            }

            [Facet(typeof(User), ""Password"", ""CreatedAt"")]
            public partial class UserDto;
        ";

        var compilation = CreateCompilation(source);
        var generator = new FacetGenerator();

        // Act
        var driver = CSharpGeneratorDriver.Create(generator)
            .RunGenerators(compilation);

        // Assert
        var runResult = driver.GetRunResult();
        var generatedSources = SourceGeneratorTestHelpers.ExtractGeneratedSources(runResult);
        
        return Verify(generatedSources)
            .UseDirectory("__snapshots__")
            .UseFileName("ExcludedProperties")
            .ScrubLines(line => line.StartsWith("// <auto-generated"));
    }

    [Fact]
    public Task FacetGenerator_WithRecordKind_GeneratesRecord()
    {
        // Arrange
        var source = @"
            using Facet;
            
            public class Product
            {
                public int Id { get; set; }
                public string Name { get; set; }
                public string Description { get; set; }
                public decimal Price { get; set; }
                public bool IsAvailable { get; set; }
            }

            [Facet(typeof(Product), Kind = FacetKind.Record)]
            public partial record ProductDto;
        ";

        var compilation = CreateCompilation(source);
        var generator = new FacetGenerator();

        // Act
        var driver = CSharpGeneratorDriver.Create(generator)
            .RunGenerators(compilation);

        // Assert
        var runResult = driver.GetRunResult();
        var generatedSources = SourceGeneratorTestHelpers.ExtractGeneratedSources(runResult);
        
        return Verify(generatedSources)
            .UseDirectory("__snapshots__")
            .UseFileName("RecordKind")
            .ScrubLines(line => line.StartsWith("// <auto-generated"));
    }

    [Fact]
    public Task FacetGenerator_WithStructKind_GeneratesStruct()
    {
        // Arrange
        var source = @"
            using Facet;
            
            public class Product
            {
                public int Id { get; set; }
                public string Name { get; set; }
                public decimal Price { get; set; }
                public bool IsAvailable { get; set; }
            }

            [Facet(typeof(Product), Kind = FacetKind.Struct)]
            public partial struct ProductSummary;
        ";

        var compilation = CreateCompilation(source);
        var generator = new FacetGenerator();

        // Act
        var driver = CSharpGeneratorDriver.Create(generator)
            .RunGenerators(compilation);

        // Assert
        var runResult = driver.GetRunResult();
        var generatedSources = SourceGeneratorTestHelpers.ExtractGeneratedSources(runResult);
        
        return Verify(generatedSources)
            .UseDirectory("__snapshots__")
            .UseFileName("StructKind")
            .ScrubLines(line => line.StartsWith("// <auto-generated"));
    }

    [Fact]
    public Task FacetGenerator_WithRecordStructKind_GeneratesRecordStruct()
    {
        // Arrange
        var source = @"
            using Facet;
            
            public class User
            {
                public int Id { get; set; }
                public string FirstName { get; set; }
                public string LastName { get; set; }
                public string Email { get; set; }
                public bool IsActive { get; set; }
            }

            [Facet(typeof(User), Kind = FacetKind.RecordStruct)]
            public partial record struct UserSummary;
        ";

        var compilation = CreateCompilation(source);
        var generator = new FacetGenerator();

        // Act
        var driver = CSharpGeneratorDriver.Create(generator)
            .RunGenerators(compilation);

        // Assert
        var runResult = driver.GetRunResult();
        var generatedSources = SourceGeneratorTestHelpers.ExtractGeneratedSources(runResult);
        
        return Verify(generatedSources)
            .UseDirectory("__snapshots__")
            .UseFileName("RecordStructKind")
            .ScrubLines(line => line.StartsWith("// <auto-generated"));
    }

    [Fact]
    public Task FacetGenerator_WithCustomProperties_GeneratesWithAdditionalMembers()
    {
        // Arrange
        var source = @"
            using Facet;
            
            public class User
            {
                public int Id { get; set; }
                public string FirstName { get; set; }
                public string LastName { get; set; }
                public string Email { get; set; }
                public DateTime DateOfBirth { get; set; }
            }

            [Facet(typeof(User))]
            public partial class UserDto
            {
                public string FullName { get; set; } = string.Empty;
                public int Age { get; set; }
            }
        ";

        var compilation = CreateCompilation(source);
        var generator = new FacetGenerator();

        // Act
        var driver = CSharpGeneratorDriver.Create(generator)
            .RunGenerators(compilation);

        // Assert
        var runResult = driver.GetRunResult();
        var generatedSources = SourceGeneratorTestHelpers.ExtractGeneratedSources(runResult);
        
        return Verify(generatedSources)
            .UseDirectory("__snapshots__")
            .UseFileName("CustomProperties")
            .ScrubLines(line => line.StartsWith("// <auto-generated"));
    }

    [Theory]
    [InlineData("Class", "FacetKind.Class")]
    [InlineData("Record", "FacetKind.Record")]
    [InlineData("Struct", "FacetKind.Struct")]
    [InlineData("RecordStruct", "FacetKind.RecordStruct")]
    public Task FacetGenerator_WithDifferentKinds_GeneratesCorrectType(string testName, string facetKind)
    {
        // Arrange
        var source = $@"
            using Facet;
            
            public class TestEntity
            {{
                public int Id {{ get; set; }}
                public string Name {{ get; set; }}
                public decimal Value {{ get; set; }}
            }}

            [Facet(typeof(TestEntity), Kind = {facetKind})]
            public partial {GetTypeDeclaration(testName)} TestDto;
        ";

        var compilation = CreateCompilation(source);
        var generator = new FacetGenerator();

        // Act
        var driver = CSharpGeneratorDriver.Create(generator)
            .RunGenerators(compilation);

        // Assert
        var runResult = driver.GetRunResult();
        var generatedSources = SourceGeneratorTestHelpers.ExtractGeneratedSources(runResult);
        
        return Verify(generatedSources)
            .UseDirectory("__snapshots__")
            .UseMethodName($"Generator_{testName}")
            .ScrubLines(line => line.StartsWith("// <auto-generated"));
    }

    [Fact]
    public void FacetGenerator_DebugTest_ShowsGeneratorBehavior()
    {
        // Arrange
        var source = @"
            using Facet;
            
            public class User
            {
                public int Id { get; set; }
                public string FirstName { get; set; }
                public string LastName { get; set; }
                public string Email { get; set; }
            }

            [Facet(typeof(User))]
            public partial class UserDto;
        ";

        var compilation = CreateCompilation(source);
        var generator = new FacetGenerator();

        // Debug: Check if compilation has errors
        var diagnostics = compilation.GetDiagnostics();
        _output.WriteLine($"=== Compilation Diagnostics ({diagnostics.Length}) ===");
        foreach (var diagnostic in diagnostics)
        {
            _output.WriteLine($"  {diagnostic.Severity}: {diagnostic.Id} - {diagnostic.GetMessage()}");
        }

        // Check what assemblies are referenced
        _output.WriteLine($"=== Referenced Assemblies ({compilation.References.Count()}) ===");
        foreach (var reference in compilation.References)
        {
            if (reference is PortableExecutableReference portableRef)
            {
                _output.WriteLine($"  {portableRef.FilePath}");
            }
        }

        // Act
        var driver = CSharpGeneratorDriver.Create(generator)
            .RunGenerators(compilation);

        // Debug: Check the generator results
        var result = driver.GetRunResult();
        _output.WriteLine($"=== Generator Results ===");
        _output.WriteLine($"Generated {result.Results.Length} results");
        
        foreach (var generatedResult in result.Results)
        {
            _output.WriteLine($"Generator: {generatedResult.Generator.GetType().Name}");
            _output.WriteLine($"Generated sources: {generatedResult.GeneratedSources.Length}");
            
            foreach (var generatedSource in generatedResult.GeneratedSources)
            {
                _output.WriteLine($"  Source: {generatedSource.HintName}");
                _output.WriteLine($"  Content length: {generatedSource.SourceText.Length}");
                if (generatedSource.SourceText.Length < 1000)
                {
                    _output.WriteLine($"  Content: {generatedSource.SourceText}");
                }
            }
            
            _output.WriteLine($"Diagnostics: {generatedResult.Diagnostics.Length}");
            foreach (var diagnostic in generatedResult.Diagnostics)
            {
                _output.WriteLine($"  Generator diagnostic: {diagnostic.Severity} - {diagnostic.GetMessage()}");
            }
        }

        // Check for compilation diagnostics
        var compilationDiagnostics = compilation.GetDiagnostics();
        _output.WriteLine($"=== Compilation Diagnostics ({compilationDiagnostics.Length}) ===");
        foreach (var diagnostic in compilationDiagnostics)
        {
            _output.WriteLine($"  {diagnostic.Severity}: {diagnostic.Id} - {diagnostic.GetMessage()}");
        }

        // Basic assertions
        Assert.Single(result.Results);
        // We expect at least one source file generated if the generator works
        // If this fails, the generator isn't finding the attribute
    }

    [Fact]
    public Task FacetGenerator_WithInvalidEntity_HandlesGracefully()
    {
        // Arrange - Entity without properties should generate diagnostics
        var source = @"
            using Facet;
            
            public class EmptyEntity
            {
                // No properties - this should be handled gracefully
            }

            [Facet(typeof(EmptyEntity))]
            public partial class EmptyDto;
        ";

        var compilation = CreateCompilation(source);
        var generator = new FacetGenerator();

        // Act
        var driver = CSharpGeneratorDriver.Create(generator)
            .RunGenerators(compilation);

        // Assert - Verify.SourceGenerators will capture diagnostics
        var runResult = driver.GetRunResult();
        var generatedSources = SourceGeneratorTestHelpers.ExtractGeneratedSources(runResult);
        
        return Verify(generatedSources)
            .UseDirectory("__snapshots__")
            .UseFileName("InvalidEntity")
            .ScrubLines(line => line.StartsWith("// <auto-generated"));
    }

    private static string GetTypeDeclaration(string testName)
    {
        return testName switch
        {
            "Class" => "class",
            "Record" => "record",
            "Struct" => "struct", 
            "RecordStruct" => "record struct",
            _ => "class"
        };
    }

    private static Compilation CreateCompilation(string source)
    {
        return CSharpCompilation.Create(
            "TestAssembly",
            syntaxTrees: new[] { CSharpSyntaxTree.ParseText(source) },
            references: GetMetadataReferences(),
            options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
    }

    private static MetadataReference[] GetMetadataReferences()
    {
        // Get all necessary references for compilation
        var assemblies = AppDomain.CurrentDomain.GetAssemblies()
            .Where(a => !a.IsDynamic && !string.IsNullOrWhiteSpace(a.Location))
            .ToList();

        // Explicitly ensure Facet assembly is included
        var facetAssembly = typeof(FacetAttribute).Assembly;
        if (!assemblies.Contains(facetAssembly))
        {
            assemblies.Add(facetAssembly);
        }

        return assemblies
            .Select(a => MetadataReference.CreateFromFile(a.Location))
            .ToArray();
    }

}