using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Facet.Extensions.EFCore.Design;

/// <summary>
/// Serializes the finalized EF Core <see cref="IModel"/> to the Facet EF model manifest —
/// a committed, diff-friendly file the Facet source generator reads (as an AdditionalFile)
/// to make <c>[GenerateDtos(ExcludeNavigationProperties = true)]</c> follow the model's own
/// designation instead of a symbol heuristic: properties EF maps as scalar or complex data
/// are kept, and navigations, skip navigations, owned references, and EF-ignored properties
/// are dropped.
/// </summary>
/// <remarks>
/// The format is deliberately line-based rather than JSON so the netstandard2.0 generator
/// can consume it with zero parsing dependencies (a JSON reader cannot be assumed in every
/// compiler host without shipping one inside the analyzer). One record per line:
/// <code>
/// version 1
/// entity Full.Type.Name
/// scalar PropertyName     — mapped scalar column (kept in DTOs)
/// complex PropertyName    — mapped complex/value-object property (kept in DTOs)
/// nav PropertyName        — reference/collection navigation (dropped)
/// owned PropertyName      — navigation to an owned type (dropped; opt back in via IncludeProperties)
/// skipnav PropertyName    — many-to-many skip navigation (dropped)
/// </code>
/// Lines starting with '#' are comments. Unknown record kinds are ignored by readers, so the
/// format can grow without breaking older generators. Properties of an entity's CLR type that
/// appear on no line at all are EF-ignored and are dropped from DTOs as well.
/// </remarks>
public static class FacetEfModelManifest
{
    /// <summary>
    /// File extension the Facet generator discovers manifests by. Wire the file up with
    /// <c>&lt;AdditionalFiles Include="Migrations/*.facetmodel" /&gt;</c> in the project that
    /// declares <c>[GenerateDtos]</c> attributes.
    /// </summary>
    public const string FileExtension = ".facetmodel";

    /// <summary>Builds the manifest text for <paramref name="model"/>.</summary>
    /// <param name="model">The finalized model (design-time or runtime).</param>
    /// <param name="contextName">Optional context name recorded in the header comment.</param>
    public static string Build(IModel model, string? contextName = null)
    {
        if (model == null) throw new ArgumentNullException(nameof(model));

        var entities = CollectEntities(model);

        var sb = new StringBuilder();
        sb.AppendLine("# Facet EF model manifest. Generated by Facet.Extensions.EFCore at design time");
        sb.AppendLine("# (dotnet ef migrations add/remove); do not edit by hand. Commit this file: the");
        sb.AppendLine("# Facet source generator reads it as an AdditionalFile so ExcludeNavigationProperties");
        sb.AppendLine("# follows the EF model exactly.");
        if (!string.IsNullOrEmpty(contextName))
        {
            sb.AppendLine($"# context: {contextName}");
        }

        sb.AppendLine("version 1");

        foreach (var entity in entities.OrderBy(e => e.Key, StringComparer.Ordinal))
        {
            sb.AppendLine();
            sb.AppendLine($"entity {entity.Key}");
            AppendMembers(sb, "scalar", entity.Value.Scalars);
            AppendMembers(sb, "complex", entity.Value.ComplexMembers);
            AppendMembers(sb, "nav", entity.Value.Navigations);
            AppendMembers(sb, "owned", entity.Value.OwnedNavigations);
            AppendMembers(sb, "skipnav", entity.Value.SkipNavigations);
        }

        return sb.ToString();
    }

    /// <summary>
    /// Writes the manifest for <paramref name="model"/> to
    /// <c>{directory}/{contextName}.facetmodel</c> and returns the file path.
    /// </summary>
    public static string Write(IModel model, string directory, string contextName)
    {
        if (directory == null) throw new ArgumentNullException(nameof(directory));
        if (string.IsNullOrWhiteSpace(contextName)) throw new ArgumentException("A context name is required.", nameof(contextName));

        var path = Path.Combine(directory, contextName + FileExtension);
        Directory.CreateDirectory(directory);
        File.WriteAllText(path, Build(model, contextName));
        return path;
    }

    private static void AppendMembers(StringBuilder sb, string kind, SortedSet<string> names)
    {
        foreach (var name in names)
        {
            sb.AppendLine($"{kind} {name}");
        }
    }

    private sealed class EntityRecord
    {
        public SortedSet<string> Scalars { get; } = new(StringComparer.Ordinal);
        public SortedSet<string> ComplexMembers { get; } = new(StringComparer.Ordinal);
        public SortedSet<string> Navigations { get; } = new(StringComparer.Ordinal);
        public SortedSet<string> OwnedNavigations { get; } = new(StringComparer.Ordinal);
        public SortedSet<string> SkipNavigations { get; } = new(StringComparer.Ordinal);
    }

    private static Dictionary<string, EntityRecord> CollectEntities(IModel model)
    {
        // Keyed by CLR type name: several entity types can share one CLR type (an owned type
        // used by multiple owners, shared-type entities), and the generator matches on the
        // [GenerateDtos] source type — so categories are unioned per CLR type. A property
        // mapped as data anywhere is kept.
        var entities = new Dictionary<string, EntityRecord>(StringComparer.Ordinal);

        foreach (var entityType in model.GetEntityTypes())
        {
            var clrType = entityType.ClrType;

            // Property bags (Dictionary<string, object> shared-type entities) and generic CLR
            // types have no stable, attribute-addressable type name; [GenerateDtos] cannot
            // target them, so they are omitted rather than emitted with an ambiguous name.
            if (entityType.IsPropertyBag || clrType.IsGenericType || clrType.FullName == null)
            {
                continue;
            }

            // Nested types print as Outer+Nested in reflection; the generator compares
            // against Roslyn display strings, which use dots.
            var clrName = clrType.FullName.Replace('+', '.');

            if (!entities.TryGetValue(clrName, out var record))
            {
                record = new EntityRecord();
                entities.Add(clrName, record);
            }

            foreach (var property in entityType.GetProperties())
            {
                // Shadow, field-mapped, and indexer properties have no CLR property for the
                // generator to keep or drop.
                if (property.IsShadowProperty() || property.IsIndexerProperty() || property.PropertyInfo == null) continue;
                record.Scalars.Add(property.Name);
            }

            foreach (var complexProperty in entityType.GetComplexProperties())
            {
                if (complexProperty.IsShadowProperty() || complexProperty.PropertyInfo == null) continue;
                record.ComplexMembers.Add(complexProperty.Name);
            }

            foreach (var navigation in entityType.GetNavigations())
            {
                if (navigation.IsShadowProperty() || navigation.PropertyInfo == null) continue;
                var target = navigation.TargetEntityType.IsOwned() ? record.OwnedNavigations : record.Navigations;
                target.Add(navigation.Name);
            }

            foreach (var skipNavigation in entityType.GetSkipNavigations())
            {
                if (skipNavigation.IsShadowProperty() || skipNavigation.PropertyInfo == null) continue;
                record.SkipNavigations.Add(skipNavigation.Name);
            }
        }

        return entities;
    }
}
