using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Facet.Extensions.EFCore.Design;

/// <summary>
/// Serializes the finalized EF Core <see cref="IModel"/> to the Facet EF model manifest —
/// a committed, diff-friendly JSON file the Facet source generator reads (as an
/// AdditionalFile) to make <c>[GenerateDtos(ExcludeNavigationProperties = true)]</c> follow
/// the model's own designation instead of a symbol heuristic: properties EF maps as scalar
/// or complex data are kept, and navigations, skip navigations, owned references, and
/// EF-ignored properties are dropped.
/// </summary>
/// <remarks>
/// Shape (member arrays are sorted and empty categories omitted, so output is deterministic
/// and diffs stay minimal):
/// <code>
/// {
///   "version": 1,
///   "context": "MyDbContext",
///   "entities": [
///     {
///       "clrType": "My.Domain.Blog",
///       "scalar": ["Id", "Title"],      // mapped scalar columns (kept in DTOs)
///       "complex": ["HomeAddress"],     // mapped complex/value-object members (kept)
///       "nav": ["Posts"],               // reference/collection navigations (dropped)
///       "owned": ["Settings"],          // owned references (dropped; IncludeProperties opts back in)
///       "skipnav": ["Labels"],          // many-to-many skip navigations (dropped)
///       "ignored": ["Secret"],          // explicitly ignored members ([NotMapped]/Ignore(); dropped)
///       "service": ["Loader"]           // service properties (ILazyLoader etc.; dropped)
///     }
///   ]
/// }
/// </code>
/// Together the categories enumerate every member the model has an opinion on, which is what
/// lets the generator treat a settable property in none of them as a stale-manifest signal
/// (FAC106) instead of silently dropping it. Readers ignore unknown properties, so the format
/// can grow without breaking older generators; a changed <c>version</c> makes older readers
/// ignore the file entirely.
/// Ignored members are only recoverable from convention-capable models (the design-time
/// model the migrations scaffolder sees, or a DbContext.Model built without a compiled
/// model); on compiled models the category is omitted.
/// </remarks>
public static class FacetEfModelManifest
{
    /// <summary>
    /// File name suffix the Facet generator discovers manifests by. Wire the file up with
    /// <c>&lt;AdditionalFiles Include="Migrations/*.facetmodel.json" /&gt;</c> in the project
    /// that declares <c>[GenerateDtos]</c> attributes.
    /// </summary>
    public const string FileExtension = ".facetmodel.json";

    /// <summary>Builds the manifest JSON for <paramref name="model"/>.</summary>
    /// <param name="model">The finalized model (design-time or runtime).</param>
    /// <param name="contextName">Optional context name recorded in the manifest.</param>
    public static string Build(IModel model, string? contextName = null)
    {
        if (model == null) throw new ArgumentNullException(nameof(model));

        var entities = CollectEntities(model);

        using var stream = new MemoryStream();
        using (var writer = new Utf8JsonWriter(stream, new JsonWriterOptions { Indented = true }))
        {
            writer.WriteStartObject();
            writer.WriteString("$comment",
                "Generated by Facet.Extensions.EFCore at design time (dotnet ef migrations add/remove); do not edit. "
                + "Commit this file: the Facet source generator reads it as an AdditionalFile so "
                + "ExcludeNavigationProperties follows the EF model exactly.");
            writer.WriteNumber("version", 1);
            if (!string.IsNullOrEmpty(contextName))
            {
                writer.WriteString("context", contextName);
            }

            writer.WriteStartArray("entities");
            foreach (var entity in entities.OrderBy(e => e.Key, StringComparer.Ordinal))
            {
                writer.WriteStartObject();
                writer.WriteString("clrType", entity.Key);
                if (entity.Value.IsOwned)
                {
                    writer.WriteBoolean("isOwned", true);
                }
                WriteCategory(writer, "scalar", entity.Value.Scalars);
                WriteCategory(writer, "complex", entity.Value.ComplexMembers);
                WriteCategory(writer, "nav", entity.Value.Navigations);
                WriteCategory(writer, "owned", entity.Value.OwnedNavigations);
                WriteCategory(writer, "skipnav", entity.Value.SkipNavigations);
                WriteCategory(writer, "ignored", entity.Value.IgnoredMembers);
                WriteCategory(writer, "service", entity.Value.ServiceProperties);
                writer.WriteEndObject();
            }

            writer.WriteEndArray();
            writer.WriteEndObject();
        }

        return Encoding.UTF8.GetString(stream.ToArray()) + Environment.NewLine;
    }

    /// <summary>
    /// Writes the manifest for <paramref name="model"/> to
    /// <c>{directory}/{contextName}.facetmodel.json</c> and returns the file path.
    /// </summary>
    public static string Write(IModel model, string directory, string contextName)
    {
        if (directory == null) throw new ArgumentNullException(nameof(directory));
        if (string.IsNullOrWhiteSpace(contextName)) throw new ArgumentException("A context name is required.", nameof(contextName));

        var path = Path.Combine(directory, contextName + FileExtension);
        Directory.CreateDirectory(directory);
        File.WriteAllText(path, Build(model, contextName));
        return path;
    }

    private static void WriteCategory(Utf8JsonWriter writer, string name, SortedSet<string> members)
    {
        if (members.Count == 0)
        {
            return;
        }

        writer.WriteStartArray(name);
        foreach (var member in members)
        {
            writer.WriteStringValue(member);
        }

        writer.WriteEndArray();
    }

    private sealed class EntityRecord
    {
        public SortedSet<string> Scalars { get; } = new(StringComparer.Ordinal);
        public SortedSet<string> ComplexMembers { get; } = new(StringComparer.Ordinal);
        public SortedSet<string> Navigations { get; } = new(StringComparer.Ordinal);
        public SortedSet<string> OwnedNavigations { get; } = new(StringComparer.Ordinal);
        public SortedSet<string> SkipNavigations { get; } = new(StringComparer.Ordinal);
        public SortedSet<string> IgnoredMembers { get; } = new(StringComparer.Ordinal);
        public SortedSet<string> ServiceProperties { get; } = new(StringComparer.Ordinal);
        public bool IsOwned { get; set; }
    }

    private static Dictionary<string, EntityRecord> CollectEntities(IModel model)
    {
        // Keyed by CLR type name: several entity types can share one CLR type (an owned type
        // used by multiple owners, shared-type entities), and the generator matches on the
        // [GenerateDtos] source type — so categories are unioned per CLR type. A property
        // mapped as data anywhere is kept.
        var entities = new Dictionary<string, EntityRecord>(StringComparer.Ordinal);

        foreach (var entityType in model.GetEntityTypes())
        {
            var clrType = entityType.ClrType;

            // Property bags (Dictionary<string, object> shared-type entities) and generic CLR
            // types have no stable, attribute-addressable type name; [GenerateDtos] cannot
            // target them, so they are omitted rather than emitted with an ambiguous name.
            if (entityType.IsPropertyBag || clrType.IsGenericType || clrType.FullName == null)
            {
                continue;
            }

            // Nested types print as Outer+Nested in reflection; the generator compares
            // against Roslyn display strings, which use dots.
            var clrName = clrType.FullName.Replace('+', '.');

            if (!entities.TryGetValue(clrName, out var record))
            {
                record = new EntityRecord();
                entities.Add(clrName, record);
            }

            if (entityType.IsOwned())
            {
                record.IsOwned = true;
            }

            foreach (var property in entityType.GetProperties())
            {
                // Shadow, field-mapped, and indexer properties have no CLR property for the
                // generator to keep or drop.
                if (property.IsShadowProperty() || property.IsIndexerProperty() || property.PropertyInfo == null) continue;
                record.Scalars.Add(property.Name);
            }

            foreach (var complexProperty in entityType.GetComplexProperties())
            {
                if (complexProperty.IsShadowProperty() || complexProperty.PropertyInfo == null) continue;
                record.ComplexMembers.Add(complexProperty.Name);
            }

            foreach (var navigation in entityType.GetNavigations())
            {
                if (navigation.IsShadowProperty() || navigation.PropertyInfo == null) continue;
                var target = navigation.TargetEntityType.IsOwned() ? record.OwnedNavigations : record.Navigations;
                target.Add(navigation.Name);
            }

            foreach (var skipNavigation in entityType.GetSkipNavigations())
            {
                if (skipNavigation.IsShadowProperty() || skipNavigation.PropertyInfo == null) continue;
                record.SkipNavigations.Add(skipNavigation.Name);
            }

            foreach (var serviceProperty in entityType.GetServiceProperties())
            {
                if (serviceProperty.PropertyInfo == null) continue;
                record.ServiceProperties.Add(serviceProperty.Name);
            }

            // Explicitly ignored members ([NotMapped]/Ignore()) are only exposed on the
            // convention metadata surface, which the finalized (non-compiled) model still
            // implements; the whole inheritance chain is walked because ignores configured
            // on a base entity type are not repeated on derived ones.
            for (var currentType = entityType as IConventionEntityType; currentType != null; currentType = currentType.BaseType)
            {
                foreach (var ignoredMember in currentType.GetIgnoredMembers())
                {
                    record.IgnoredMembers.Add(ignoredMember);
                }
            }
        }

        return entities;
    }
}
