using Facet.Generators.Shared;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Facet.Generators.FacetMapGenerators;

internal static class FacetMapCodeBuilder
{
    public static string Generate(FacetMapTargetModel model)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Linq.Expressions;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();

        if (!string.IsNullOrWhiteSpace(model.Namespace))
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        var containingIndent = GenerateContainingTypeHierarchy(sb, model);
        var memberIndent = containingIndent + "    ";

        sb.AppendLine($"{containingIndent}{model.Accessibility} static partial class {model.MarkerClassName}");
        sb.AppendLine($"{containingIndent}{{");

        GenerateToTargetExtension(sb, model, memberIndent);

        if (model.GenerateToSource)
        {
            GenerateToSourceExtension(sb, model, memberIndent);
            GenerateApplyToSourceExtension(sb, model, memberIndent);
        }

        if (model.GenerateProjection)
        {
            GenerateProjectionProperty(sb, model, memberIndent);
        }

        // Generate projection map action helper when configuration uses IFacetProjectionMapConfiguration
        if (model.ConfigurationTypeName != null && !model.HasMapConfiguration && model.HasProjectionMapConfiguration)
        {
            GenerateProjectionMapAction(sb, model, memberIndent);
        }

        sb.AppendLine($"{containingIndent}}}");

        CloseContainingTypeHierarchy(sb, model);

        return sb.ToString();
    }

    private static void GenerateToTargetExtension(StringBuilder sb, FacetMapTargetModel model, string indent)
    {
        var sourceParam = "source";
        var targetSimple = GetSimpleTypeName(model.TargetTypeName);
        var sourceSimple = GetSimpleTypeName(model.SourceTypeName);

        sb.AppendLine($"{indent}/// <summary>");
        sb.AppendLine($"{indent}/// Maps a <see cref=\"{sourceSimple}\"/> instance to a new <see cref=\"{targetSimple}\"/> instance.");
        sb.AppendLine($"{indent}/// </summary>");
        sb.AppendLine($"{indent}public static {model.TargetTypeName} To{model.TargetTypeSimpleName}(this {model.SourceTypeName} {sourceParam})");
        sb.AppendLine($"{indent}{{");

        sb.AppendLine($"{indent}    if ({sourceParam} == null) throw new ArgumentNullException(nameof({sourceParam}));");
        sb.AppendLine();

        var sourcePropertyNames = GetSourcePropertyNames(model);
        var hasInitOnlyMembers = model.Members.Any(m => m.IsTargetInitOnly);
        var hasConfiguration = model.ConfigurationTypeName != null;
        var hasBeforeMap = model.BeforeMapConfigurationTypeName != null;
        var hasAfterMap = model.AfterMapConfigurationTypeName != null;
        var needsTargetVariable = hasInitOnlyMembers || hasConfiguration || hasBeforeMap || hasAfterMap;

        if (hasInitOnlyMembers)
        {
            // Mixed: use object initializer for init-only, then statements for mutable
            var initMembers = model.Members.Where(m => m.IsTargetInitOnly).ToList();
            var mutableMembers = model.Members.Where(m => !m.IsTargetInitOnly).ToList();

            sb.AppendLine($"{indent}    var target = new {model.TargetTypeName}");
            sb.AppendLine($"{indent}    {{");
            for (int i = 0; i < initMembers.Count; i++)
            {
                var member = initMembers[i];
                var value = GetForwardValueExpression(member, sourceParam, sourcePropertyNames);
                var trailing = i < initMembers.Count - 1 ? "," : "";
                sb.AppendLine($"{indent}        {member.Name} = {value}{trailing}");
            }
            sb.AppendLine($"{indent}    }};");

            if (hasBeforeMap)
            {
                sb.AppendLine();
                sb.AppendLine($"{indent}    {model.BeforeMapConfigurationTypeName}.BeforeMap({sourceParam}, target);");
            }

            foreach (var member in mutableMembers)
            {
                var value = GetForwardValueExpression(member, sourceParam, sourcePropertyNames);
                sb.AppendLine($"{indent}    target.{member.Name} = {value};");
            }
        }
        else if (needsTargetVariable)
        {
            // Has configurations - need a variable to pass to Map/BeforeMap/AfterMap
            sb.AppendLine($"{indent}    var target = new {model.TargetTypeName}();");

            if (hasBeforeMap)
            {
                sb.AppendLine();
                sb.AppendLine($"{indent}    {model.BeforeMapConfigurationTypeName}.BeforeMap({sourceParam}, target);");
            }

            foreach (var member in model.Members)
            {
                var value = GetForwardValueExpression(member, sourceParam, sourcePropertyNames);
                sb.AppendLine($"{indent}    target.{member.Name} = {value};");
            }
        }
        else
        {
            // Simple case: use object initializer (same style as Facet's FromSource)
            var propertyAssignments = new System.Collections.Generic.List<string>();
            foreach (var member in model.Members)
            {
                var value = GetForwardValueExpression(member, sourceParam, sourcePropertyNames);
                propertyAssignments.Add($"{indent}        {member.Name} = {value}");
            }

            sb.AppendLine($"{indent}    return new {model.TargetTypeName}");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine(string.Join(",\n", propertyAssignments));
            sb.AppendLine($"{indent}    }};");
            sb.AppendLine($"{indent}}}");
            return;
        }

        if (hasConfiguration)
        {
            sb.AppendLine();
            sb.AppendLine($"{indent}    {GetMappingCall(model, sourceParam, "target")};");
        }

        if (hasAfterMap)
        {
            sb.AppendLine();
            sb.AppendLine($"{indent}    {model.AfterMapConfigurationTypeName}.AfterMap({sourceParam}, target);");
        }

        sb.AppendLine();
        sb.AppendLine($"{indent}    return target;");
        sb.AppendLine($"{indent}}}");
    }

    private static void GenerateToSourceExtension(StringBuilder sb, FacetMapTargetModel model, string indent)
    {
        var dtoParam = "dto";
        var targetSimple = GetSimpleTypeName(model.TargetTypeName);
        var sourceSimple = GetSimpleTypeName(model.SourceTypeName);

        sb.AppendLine();
        sb.AppendLine($"{indent}/// <summary>");
        sb.AppendLine($"{indent}/// Maps a <see cref=\"{targetSimple}\"/> instance back to a new <see cref=\"{sourceSimple}\"/> instance.");
        sb.AppendLine($"{indent}/// </summary>");
        sb.AppendLine($"{indent}public static {model.SourceTypeName} To{model.SourceTypeSimpleName}(this {model.TargetTypeName} {dtoParam})");
        sb.AppendLine($"{indent}{{");

        sb.AppendLine($"{indent}    if ({dtoParam} == null) throw new ArgumentNullException(nameof({dtoParam}));");
        sb.AppendLine();

        var hasInitOnlyMembers = model.Members.Any(m => m.IsSourceInitOnly);

        if (hasInitOnlyMembers)
        {
            // Mixed init-only + mutable: use object initializer for init-only, then assign mutable
            var initMembers = model.Members.Where(m => m.IsSourceInitOnly).ToList();
            var mutableMembers = model.Members.Where(m => !m.IsSourceInitOnly).ToList();

            sb.AppendLine($"{indent}    var target = new {model.SourceTypeName}");
            sb.AppendLine($"{indent}    {{");
            for (int i = 0; i < initMembers.Count; i++)
            {
                var member = initMembers[i];
                var value = GetToSourceValueExpression(member, dtoParam);
                var trailing = i < initMembers.Count - 1 ? "," : "";
                sb.AppendLine($"{indent}        {member.SourcePropertyName} = {value}{trailing}");
            }
            sb.AppendLine($"{indent}    }};");

            foreach (var mutableMember in mutableMembers)
            {
                var value = GetToSourceValueExpression(mutableMember, dtoParam);
                sb.AppendLine($"{indent}    target.{mutableMember.SourcePropertyName} = {value};");
            }
        }
        else
        {
            // Use object initializer pattern (same as Facet's ToSource)
            var propertyAssignments = new System.Collections.Generic.List<string>();
            foreach (var member in model.Members)
            {
                var value = GetToSourceValueExpression(member, dtoParam);
                propertyAssignments.Add($"{indent}        {member.SourcePropertyName} = {value}");
            }

            if (model.ToSourceConfigurationTypeName != null)
            {
                sb.AppendLine($"{indent}    var target = new {model.SourceTypeName}");
                sb.AppendLine($"{indent}    {{");
                sb.AppendLine(string.Join(",\n", propertyAssignments));
                sb.AppendLine($"{indent}    }};");
                sb.AppendLine();
                sb.AppendLine($"{indent}    {model.ToSourceConfigurationTypeName}.Map({dtoParam}, target);");
            }
            else
            {
                sb.AppendLine($"{indent}    return new {model.SourceTypeName}");
                sb.AppendLine($"{indent}    {{");
                sb.AppendLine(string.Join(",\n", propertyAssignments));
                sb.AppendLine($"{indent}    }};");
            }
        }

        if (hasInitOnlyMembers && model.ToSourceConfigurationTypeName != null)
        {
            sb.AppendLine();
            sb.AppendLine($"{indent}    {model.ToSourceConfigurationTypeName}.Map({dtoParam}, target);");
        }

        // Return for cases where we need 'target' (init-only members or ToSourceConfiguration)
        if (hasInitOnlyMembers || model.ToSourceConfigurationTypeName != null)
        {
            sb.AppendLine();
            sb.AppendLine($"{indent}    return target;");
        }

        sb.AppendLine($"{indent}}}");
    }

    private static void GenerateApplyToSourceExtension(StringBuilder sb, FacetMapTargetModel model, string indent)
    {
        var dtoParam = "dto";
        var targetSimple = GetSimpleTypeName(model.TargetTypeName);
        var sourceSimple = GetSimpleTypeName(model.SourceTypeName);

        sb.AppendLine();
        sb.AppendLine($"{indent}/// <summary>");
        sb.AppendLine($"{indent}/// Applies the mapped properties of a <see cref=\"{targetSimple}\"/> instance onto an existing");
        sb.AppendLine($"{indent}/// <see cref=\"{sourceSimple}\"/> instance in place.");
        sb.AppendLine($"{indent}/// Properties excluded from this mapping are left unchanged on the source.");
        sb.AppendLine($"{indent}/// </summary>");
        sb.AppendLine($"{indent}/// <param name=\"{dtoParam}\">The DTO instance containing the values to apply.</param>");
        sb.AppendLine($"{indent}/// <param name=\"source\">The existing <see cref=\"{sourceSimple}\"/> instance to update.</param>");
        sb.AppendLine($"{indent}public static void ApplyTo{model.SourceTypeSimpleName}(this {model.TargetTypeName} {dtoParam}, {model.SourceTypeName} source)");
        sb.AppendLine($"{indent}{{");

        sb.AppendLine($"{indent}    if ({dtoParam} == null) throw new ArgumentNullException(nameof({dtoParam}));");
        sb.AppendLine($"{indent}    if (source == null) throw new ArgumentNullException(nameof(source));");

        var hasMappable = false;
        foreach (var member in model.Members)
        {
            if (member.IsSourceInitOnly)
                continue;

            var value = GetToSourceValueExpression(member, dtoParam);
            sb.AppendLine($"{indent}    source.{member.SourcePropertyName} = {value};");
            hasMappable = true;
        }

        if (!hasMappable)
            sb.AppendLine($"{indent}    // No settable members configured for this mapping");

        if (model.ToSourceConfigurationTypeName != null)
        {
            sb.AppendLine($"{indent}    {model.ToSourceConfigurationTypeName}.Map({dtoParam}, source);");
        }

        sb.AppendLine($"{indent}}}");
    }

    private static void GenerateProjectionProperty(StringBuilder sb, FacetMapTargetModel model, string indent)
    {
        var sourceSimple = GetSimpleTypeName(model.SourceTypeName);
        var targetSimple = GetSimpleTypeName(model.TargetTypeName);
        var sourcePropertyNames = GetSourcePropertyNames(model);

        sb.AppendLine();
        sb.AppendLine($"{indent}/// <summary>");
        sb.AppendLine($"{indent}/// LINQ projection expression for mapping <see cref=\"{sourceSimple}\"/> to <see cref=\"{targetSimple}\"/>.");
        sb.AppendLine($"{indent}/// </summary>");
        sb.AppendLine($"{indent}public static Expression<Func<{model.SourceTypeName}, {model.TargetTypeName}>> {model.SourceTypeSimpleName}To{model.TargetTypeSimpleName}Projection =>");
        sb.AppendLine($"{indent}    source => new {model.TargetTypeName}");
        sb.AppendLine($"{indent}    {{");

        var projectionMembers = model.Members
            .Where(m => m.MapFromIncludeInProjection && !m.IsNestedFacet)
            .ToList();

        for (int i = 0; i < projectionMembers.Count; i++)
        {
            var member = projectionMembers[i];
            var trailing = i < projectionMembers.Count - 1 ? "," : "";

            var value = GetProjectionValueExpression(member, "source", sourcePropertyNames);
            sb.AppendLine($"{indent}        {member.Name} = {value}{trailing}");
        }

        sb.AppendLine($"{indent}    }};");
    }

    /// <summary>
    /// Gets the forward mapping expression for a member (source to target).
    /// For nested FacetMap types, generates extension method calls (e.g., source.Address.ToAddressDto()).
    /// For regular members, delegates to the shared ExpressionBuilder.
    /// </summary>
    private static string GetForwardValueExpression(FacetMapMember member, string sourceParam, HashSet<string> sourcePropertyNames)
    {
        if (member.IsNestedFacet && member.NestedTargetTypeSimpleName != null)
        {
            bool isNullable = member.TypeName.EndsWith("?");
            var extensionMethod = $"To{member.NestedTargetTypeSimpleName}";

            if (member.IsCollection && member.CollectionWrapper != null)
            {
                // Collection nested: source.Addresses.Select(x => x.ToAddressDto()).ToList()
                var projection = $"{sourceParam}.{member.SourcePropertyName}.Select(x => x.{extensionMethod}())";
                var collectionExpression = WrapCollectionProjection(projection, member.CollectionWrapper);

                if (isNullable)
                {
                    return $"{sourceParam}.{member.SourcePropertyName} != null ? {collectionExpression} : null";
                }

                return $"{sourceParam}.{member.SourcePropertyName} != null ? {collectionExpression} : default!";
            }
            else
            {
                // Single nested: source.CultureInfo.ToCultureInfoDto()
                if (isNullable)
                {
                    return $"{sourceParam}.{member.SourcePropertyName} != null ? {sourceParam}.{member.SourcePropertyName}.{extensionMethod}() : null";
                }

                return $"{sourceParam}.{member.SourcePropertyName} != null ? {sourceParam}.{member.SourcePropertyName}.{extensionMethod}() : default!";
            }
        }

        // Non-nested: delegate to the shared expression builder
        var expression = ExpressionBuilder.GetSourceValueExpression(member, sourceParam, 0, false, false, sourcePropertyNames);

        // Handle nullable-to-non-nullable conversion in forward mapping (source int? -> target int)
        bool sourceIsNullable = member.SourceMemberTypeName?.EndsWith("?") ?? false;
        bool targetIsNullable = member.TypeName.EndsWith("?");
        if (sourceIsNullable && !targetIsNullable)
        {
            if (member.IsValueType)
            {
                return $"{expression} ?? default";
            }
            else
            {
                return $"{expression}!";
            }
        }

        return expression;
    }

    /// <summary>
    /// Gets a projection-safe value expression for a member.
    /// Avoids null-propagating operators (?.) which are not allowed in expression trees.
    /// </summary>
    private static string GetProjectionValueExpression(FacetMapMember member, string sourceParam, HashSet<string> sourcePropertyNames)
    {
        // Handle enum conversions with expression-tree-safe expressions
        if (member.IsEnumConversion && member.OriginalEnumTypeName != null)
        {
            bool isNullableSource = member.SourceMemberTypeName?.EndsWith("?") ?? false;

            if (member.TypeName.TrimEnd('?') == "string")
            {
                if (isNullableSource)
                {
                    // Expression-tree safe: use ternary instead of ?.
                    return $"{sourceParam}.{member.SourcePropertyName} != null ? {sourceParam}.{member.SourcePropertyName}.Value.ToString() : null";
                }
                return $"{sourceParam}.{member.SourcePropertyName}.ToString()";
            }
            else if (member.TypeName.TrimEnd('?') == "int")
            {
                if (isNullableSource)
                {
                    return $"{sourceParam}.{member.SourcePropertyName} != null ? (int?){sourceParam}.{member.SourcePropertyName}.Value : null";
                }
                return $"(int){sourceParam}.{member.SourcePropertyName}";
            }
        }

        // For non-enum members, use the shared expression builder (safe for projections)
        var expression = ExpressionBuilder.GetSourceValueExpression(member, sourceParam, 0, false, false, sourcePropertyNames);

        // Handle nullable-to-non-nullable conversion in projections (source int? -> target int)
        bool sourceIsNullable = member.SourceMemberTypeName?.EndsWith("?") ?? false;
        bool targetIsNullable = member.TypeName.EndsWith("?");
        if (sourceIsNullable && !targetIsNullable)
        {
            if (member.IsValueType)
            {
                // Expression-tree safe: use ternary with .Value for nullable value types
                return $"{sourceParam}.{member.SourcePropertyName} != null ? {sourceParam}.{member.SourcePropertyName}.Value : default";
            }
            else
            {
                return $"{expression}!";
            }
        }

        return expression;
    }

    /// <summary>
    /// Gets the reverse mapping expression for a member (target/DTO back to source).
    /// For nested FacetMap types, generates extension method calls (e.g., dto.Address.ToAddressEntity()).
    /// For regular members, uses simple property access with type conversions as needed.
    /// </summary>
    private static string GetToSourceValueExpression(FacetMapMember member, string dtoParam)
    {
        bool facetTypeIsNullable = member.TypeName.EndsWith("?");
        bool sourceTypeIsNullable = member.SourceMemberTypeName?.EndsWith("?") ?? facetTypeIsNullable;

        // Handle enum conversions in reverse (facet string/int -> source enum)
        if (member.IsEnumConversion && member.OriginalEnumTypeName != null)
        {
            return GetEnumToSourceExpression(member, dtoParam);
        }

        // Handle nested facet types in reverse via extension method calls
        if (member.IsNestedFacet && member.NestedSourceTypeSimpleName != null)
        {
            var extensionMethod = $"To{member.NestedSourceTypeSimpleName}";

            if (member.IsCollection && member.CollectionWrapper != null)
            {
                // Collection nested: dto.Addresses.Select(x => x.ToAddressEntity()).ToList()
                var sourceWrapper = member.SourceCollectionWrapper ?? member.CollectionWrapper;
                var projection = $"{dtoParam}.{member.Name}.Select(x => x.{extensionMethod}())";
                var collectionExpression = WrapCollectionProjection(projection, sourceWrapper);

                if (facetTypeIsNullable)
                {
                    return $"{dtoParam}.{member.Name} != null ? {collectionExpression} : null";
                }

                return $"{dtoParam}.{member.Name} != null ? {collectionExpression} : default!";
            }
            else
            {
                // Single nested: dto.CultureInfo.ToCultureInfoEntity()
                if (facetTypeIsNullable)
                {
                    return $"{dtoParam}.{member.Name} != null ? {dtoParam}.{member.Name}.{extensionMethod}() : null";
                }

                return $"{dtoParam}.{member.Name} != null ? {dtoParam}.{member.Name}.{extensionMethod}() : default!";
            }
        }

        // Handle nested facet collections in reverse (element types differ, need transformation)
        // This handles the case where IsNestedFacet is true but NestedSourceTypeSimpleName is null (shouldn't happen, but defensive)
        if (member.IsNestedFacet && member.IsCollection && member.CollectionWrapper != null)
        {
            var sourceWrapper = member.SourceCollectionWrapper ?? member.CollectionWrapper;
            var projection = $"{dtoParam}.{member.Name}";
            var collectionExpression = WrapCollectionProjection($"{projection}.Select(x => x)", sourceWrapper);

            if (facetTypeIsNullable)
            {
                return $"{dtoParam}.{member.Name} != null ? {collectionExpression} : null";
            }

            return $"{dtoParam}.{member.Name} != null ? {collectionExpression} : default!";
        }

        // Handle plain collections where only the collection wrapper type differs
        // (e.g., source is IList<T> but target is List<T>)
        if (member.IsCollection && member.CollectionWrapper != null && member.SourceCollectionWrapper != null)
        {
            var projection = $"{dtoParam}.{member.Name}";
            var collectionExpression = WrapCollectionProjection($"{projection}.Select(x => x)", member.SourceCollectionWrapper);

            if (facetTypeIsNullable)
            {
                return $"{dtoParam}.{member.Name} != null ? {collectionExpression} : null";
            }

            return collectionExpression;
        }

        // Handle nullable-to-non-nullable conversion
        if (facetTypeIsNullable && !sourceTypeIsNullable)
        {
            if (member.IsValueType)
            {
                return $"{dtoParam}.{member.Name} ?? default";
            }
            else
            {
                return $"{dtoParam}.{member.Name}!";
            }
        }

        return $"{dtoParam}.{member.Name}";
    }

    /// <summary>
    /// Gets the enum-to-source conversion expression for reverse mapping.
    /// </summary>
    private static string GetEnumToSourceExpression(FacetMapMember member, string dtoParam)
    {
        var enumTypeName = member.OriginalEnumTypeName!;
        bool facetTypeIsNullable = member.TypeName.EndsWith("?");
        bool sourceTypeIsNullable = member.SourceMemberTypeName?.EndsWith("?") ?? false;

        if (member.TypeName.TrimEnd('?') == "string")
        {
            if (facetTypeIsNullable && sourceTypeIsNullable)
            {
                return $"{dtoParam}.{member.Name} != null ? ({enumTypeName}?)System.Enum.Parse<{enumTypeName}>({dtoParam}.{member.Name}) : null";
            }
            else if (facetTypeIsNullable)
            {
                return $"System.Enum.Parse<{enumTypeName}>({dtoParam}.{member.Name}!)";
            }
            else
            {
                return $"System.Enum.Parse<{enumTypeName}>({dtoParam}.{member.Name})";
            }
        }
        else if (member.TypeName.TrimEnd('?') == "int")
        {
            if (facetTypeIsNullable && sourceTypeIsNullable)
            {
                return $"{dtoParam}.{member.Name} != null ? ({enumTypeName}?)({enumTypeName}){dtoParam}.{member.Name}.Value : null";
            }
            else if (facetTypeIsNullable)
            {
                return $"({enumTypeName})({dtoParam}.{member.Name} ?? default)";
            }
            else
            {
                return $"({enumTypeName}){dtoParam}.{member.Name}";
            }
        }

        return $"{dtoParam}.{member.Name}";
    }

    private static string WrapCollectionProjection(string projection, string collectionWrapper)
    {
        return collectionWrapper switch
        {
            FacetConstants.CollectionWrappers.List => $"{projection}.ToList()",
            FacetConstants.CollectionWrappers.IList => $"{projection}.ToList()",
            FacetConstants.CollectionWrappers.ICollection => $"{projection}.ToList()",
            FacetConstants.CollectionWrappers.IReadOnlyList => $"{projection}.ToList()",
            FacetConstants.CollectionWrappers.IReadOnlyCollection => $"{projection}.ToList()",
            FacetConstants.CollectionWrappers.IEnumerable => projection,
            FacetConstants.CollectionWrappers.Array or "array" => $"{projection}.ToArray()",
            FacetConstants.CollectionWrappers.Collection => $"{projection}.ToList()",
            FacetConstants.CollectionWrappers.ImmutableArray => $"{projection}.ToImmutableArray()",
            FacetConstants.CollectionWrappers.ImmutableList => $"{projection}.ToImmutableList()",
            FacetConstants.CollectionWrappers.ImmutableHashSet => $"{projection}.ToImmutableHashSet()",
            FacetConstants.CollectionWrappers.ImmutableSortedSet => $"{projection}.ToImmutableSortedSet()",
            FacetConstants.CollectionWrappers.ImmutableQueue => $"global::System.Collections.Immutable.ImmutableQueue.CreateRange({projection})",
            FacetConstants.CollectionWrappers.ImmutableStack => $"global::System.Collections.Immutable.ImmutableStack.CreateRange({projection})",
            FacetConstants.CollectionWrappers.IImmutableList => $"{projection}.ToImmutableList()",
            FacetConstants.CollectionWrappers.IImmutableSet => $"{projection}.ToImmutableHashSet()",
            FacetConstants.CollectionWrappers.IImmutableQueue => $"global::System.Collections.Immutable.ImmutableQueue.CreateRange({projection})",
            FacetConstants.CollectionWrappers.IImmutableStack => $"global::System.Collections.Immutable.ImmutableStack.CreateRange({projection})",
            _ => projection
        };
    }

    private static HashSet<string> GetSourcePropertyNames(FacetMapTargetModel model)
    {
        return new HashSet<string>(
            model.Members.Select(m => m.SourcePropertyName),
            System.StringComparer.Ordinal);
    }

    private static string GenerateContainingTypeHierarchy(StringBuilder sb, FacetMapTargetModel model)
    {
        var indent = "";
        foreach (var containingType in model.ContainingTypes)
        {
            sb.AppendLine($"{indent}partial class {containingType}");
            sb.AppendLine($"{indent}{{");
            indent += "    ";
        }
        return indent;
    }

    private static void CloseContainingTypeHierarchy(StringBuilder sb, FacetMapTargetModel model)
    {
        for (int i = model.ContainingTypes.Length - 1; i >= 0; i--)
        {
            var indent = new string(' ', i * 4);
            sb.AppendLine($"{indent}}}");
        }
    }

    private static string GetSimpleTypeName(string fullyQualifiedName)
    {
        var name = fullyQualifiedName.Replace("global::", "");
        var lastDot = name.LastIndexOf('.');
        return lastDot >= 0 ? name.Substring(lastDot + 1) : name;
    }

    /// <summary>
    /// Returns the appropriate mapping call for the configuration.
    /// When the config only implements IFacetProjectionMapConfiguration (no Map method),
    /// delegates to the compiled projection action. Otherwise calls Map() directly.
    /// </summary>
    private static string GetMappingCall(FacetMapTargetModel model, string sourceExpr, string targetExpr)
    {
        if (!model.HasMapConfiguration && model.HasProjectionMapConfiguration)
        {
            return $"__GetProjectionMapAction()({sourceExpr}, {targetExpr})";
        }
        return $"{model.ConfigurationTypeName}.Map({sourceExpr}, {targetExpr})";
    }

    /// <summary>
    /// Generates a lazily-compiled Action that executes the projection-based
    /// ConfigureProjection expressions. Called when the configuration type
    /// implements IFacetProjectionMapConfiguration but not IFacetMapConfiguration.
    /// </summary>
    private static void GenerateProjectionMapAction(StringBuilder sb, FacetMapTargetModel model, string memberIndent)
    {
        var src = model.SourceTypeName;
        var tgt = model.TargetTypeName;
        var bodyIndent = memberIndent + "    ";

        sb.AppendLine();
        sb.AppendLine($"{memberIndent}private static global::System.Action<{src}, {tgt}>? __projectionMapAction;");
        sb.AppendLine();
        sb.AppendLine($"{memberIndent}private static global::System.Action<{src}, {tgt}> __GetProjectionMapAction()");
        sb.AppendLine($"{memberIndent}{{");
        sb.AppendLine($"{bodyIndent}return global::System.Threading.LazyInitializer.EnsureInitialized(ref __projectionMapAction, () =>");
        sb.AppendLine($"{bodyIndent}{{");

        var innerIndent = bodyIndent + "    ";

        sb.AppendLine($"{innerIndent}var __sourceParam = global::System.Linq.Expressions.Expression.Parameter(typeof({src}), \"source\");");
        sb.AppendLine($"{innerIndent}var __targetParam = global::System.Linq.Expressions.Expression.Parameter(typeof({tgt}), \"target\");");
        sb.AppendLine($"{innerIndent}var __assignments = new global::System.Collections.Generic.List<global::System.Linq.Expressions.Expression>();");
        sb.AppendLine();

        sb.AppendLine($"{innerIndent}var __builder = new global::Facet.Mapping.FacetProjectionBuilder<{src}, {tgt}>();");
        sb.AppendLine($"{innerIndent}{model.ConfigurationTypeName}.ConfigureProjection(__builder);");
        sb.AppendLine($"{innerIndent}foreach (var (__member, __expr) in __builder.Mappings)");
        sb.AppendLine($"{innerIndent}{{");
        sb.AppendLine($"{innerIndent}    var __body = global::Facet.Mapping.ParameterReplacer.Replace(__expr, __sourceParam);");
        sb.AppendLine($"{innerIndent}    __assignments.Add(global::System.Linq.Expressions.Expression.Assign(");
        sb.AppendLine($"{innerIndent}        global::System.Linq.Expressions.Expression.MakeMemberAccess(__targetParam, __member), __body));");
        sb.AppendLine($"{innerIndent}}}");
        sb.AppendLine();
        sb.AppendLine($"{innerIndent}if (__assignments.Count == 0)");
        sb.AppendLine($"{innerIndent}    return (_, _) => {{ }};");
        sb.AppendLine();
        sb.AppendLine($"{innerIndent}var __block = global::System.Linq.Expressions.Expression.Block(__assignments);");
        sb.AppendLine($"{innerIndent}return global::System.Linq.Expressions.Expression.Lambda<global::System.Action<{src}, {tgt}>>(");
        sb.AppendLine($"{innerIndent}    __block, __sourceParam, __targetParam).Compile();");

        sb.AppendLine($"{bodyIndent}}})!;");
        sb.AppendLine($"{memberIndent}}}");
    }
}
