using Facet.Generators.Shared;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Facet.Generators.FacetMapGenerators;

internal static class FacetMapCodeBuilder
{
    public static string Generate(FacetMapTargetModel model)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Linq.Expressions;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();

        if (!string.IsNullOrWhiteSpace(model.Namespace))
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        var containingIndent = GenerateContainingTypeHierarchy(sb, model);
        var memberIndent = containingIndent + "    ";

        sb.AppendLine($"{containingIndent}{model.Accessibility} static partial class {model.MarkerClassName}");
        sb.AppendLine($"{containingIndent}{{");

        GenerateToTargetExtension(sb, model, memberIndent);

        if (model.GenerateToSource)
        {
            GenerateToSourceExtension(sb, model, memberIndent);
        }

        if (model.GenerateProjection)
        {
            GenerateProjectionProperty(sb, model, memberIndent);
        }

        sb.AppendLine($"{containingIndent}}}");

        CloseContainingTypeHierarchy(sb, model);

        return sb.ToString();
    }

    private static void GenerateToTargetExtension(StringBuilder sb, FacetMapTargetModel model, string indent)
    {
        var sourceParam = "source";
        var targetSimple = GetSimpleTypeName(model.TargetTypeName);
        var sourceSimple = GetSimpleTypeName(model.SourceTypeName);

        sb.AppendLine($"{indent}/// <summary>");
        sb.AppendLine($"{indent}/// Maps a <see cref=\"{sourceSimple}\"/> instance to a new <see cref=\"{targetSimple}\"/> instance.");
        sb.AppendLine($"{indent}/// </summary>");
        sb.AppendLine($"{indent}public static {model.TargetTypeName} To{model.TargetTypeSimpleName}(this {model.SourceTypeName} {sourceParam})");
        sb.AppendLine($"{indent}{{");

        sb.AppendLine($"{indent}    if ({sourceParam} == null) throw new ArgumentNullException(nameof({sourceParam}));");
        sb.AppendLine();
        sb.AppendLine($"{indent}    var target = new {model.TargetTypeName}();");

        foreach (var member in model.Members)
        {
            var assignment = GeneratePropertyAssignment(member, sourceParam, "target", model);
            sb.AppendLine($"{indent}    {assignment}");
        }

        if (model.ConfigurationTypeName != null)
        {
            sb.AppendLine();
            sb.AppendLine($"{indent}    {model.ConfigurationTypeName}.Map({sourceParam}, target);");
        }

        sb.AppendLine();
        sb.AppendLine($"{indent}    return target;");
        sb.AppendLine($"{indent}}}");
    }

    private static void GenerateToSourceExtension(StringBuilder sb, FacetMapTargetModel model, string indent)
    {
        var sourceParam = "dto";
        var targetSimple = GetSimpleTypeName(model.TargetTypeName);
        var sourceSimple = GetSimpleTypeName(model.SourceTypeName);

        sb.AppendLine();
        sb.AppendLine($"{indent}/// <summary>");
        sb.AppendLine($"{indent}/// Maps a <see cref=\"{targetSimple}\"/> instance back to a new <see cref=\"{sourceSimple}\"/> instance.");
        sb.AppendLine($"{indent}/// </summary>");
        sb.AppendLine($"{indent}public static {model.SourceTypeName} To{model.SourceTypeSimpleName}(this {model.TargetTypeName} {sourceParam})");
        sb.AppendLine($"{indent}{{");

        sb.AppendLine($"{indent}    if ({sourceParam} == null) throw new ArgumentNullException(nameof({sourceParam}));");
        sb.AppendLine();

        if (model.SourceHasPositionalConstructor)
        {
            // For positional records, use object initializer (the record still has a parameterless-ish path via with{})
            sb.AppendLine($"{indent}    var target = new {model.SourceTypeName}();");
        }
        else
        {
            sb.AppendLine($"{indent}    var target = new {model.SourceTypeName}();");
        }

        foreach (var member in model.Members)
        {
            var assignment = GeneratePropertyAssignment(member, sourceParam, "target", model, reverse: true);
            sb.AppendLine($"{indent}    {assignment}");
        }

        if (model.ToSourceConfigurationTypeName != null)
        {
            sb.AppendLine();
            sb.AppendLine($"{indent}    {model.ToSourceConfigurationTypeName}.Map({sourceParam}, target);");
        }

        sb.AppendLine();
        sb.AppendLine($"{indent}    return target;");
        sb.AppendLine($"{indent}}}");
    }

    private static void GenerateProjectionProperty(StringBuilder sb, FacetMapTargetModel model, string indent)
    {
        var sourceSimple = GetSimpleTypeName(model.SourceTypeName);
        var targetSimple = GetSimpleTypeName(model.TargetTypeName);

        sb.AppendLine();
        sb.AppendLine($"{indent}/// <summary>");
        sb.AppendLine($"{indent}/// LINQ projection expression for mapping <see cref=\"{sourceSimple}\"/> to <see cref=\"{targetSimple}\"/>.");
        sb.AppendLine($"{indent}/// </summary>");
        sb.AppendLine($"{indent}public static Expression<Func<{model.SourceTypeName}, {model.TargetTypeName}>> {model.TargetTypeSimpleName}Projection =>");
        sb.AppendLine($"{indent}    source => new {model.TargetTypeName}");
        sb.AppendLine($"{indent}    {{");

        for (int i = 0; i < model.Members.Length; i++)
        {
            var member = model.Members[i];
            var trailing = i < model.Members.Length - 1 ? "," : "";

            if (member.IsCollection && member.CollectionElementType != null)
            {
                sb.AppendLine($"{indent}        {member.Name} = source.{member.SourcePropertyName}.Select(x => x).ToList(){trailing}");
            }
            else
            {
                sb.AppendLine($"{indent}        {member.Name} = source.{member.SourcePropertyName}{trailing}");
            }
        }

        sb.AppendLine($"{indent}    }};");
    }

    private static string GeneratePropertyAssignment(FacetMapMember member, string sourceVar, string targetVar, FacetMapTargetModel model, bool reverse = false)
    {
        var sourceProp = reverse ? member.Name : member.SourcePropertyName;
        var targetProp = reverse ? member.SourcePropertyName : member.Name;

        if (member.IsCollection && member.CollectionWrapper != null)
        {
            var nullCheck = member.IsNullable ? $"{sourceVar}.{sourceProp} != null ? " : "";
            var nullEnd = member.IsNullable ? " : null" : "";

            if (member.CollectionWrapper == "array")
            {
                return $"{targetVar}.{targetProp} = {nullCheck}{sourceVar}.{sourceProp}.ToArray(){nullEnd};";
            }
            else
            {
                return $"{targetVar}.{targetProp} = {nullCheck}{sourceVar}.{sourceProp}.ToList(){nullEnd};";
            }
        }

        return $"{targetVar}.{targetProp} = {sourceVar}.{sourceProp};";
    }

    private static string GenerateContainingTypeHierarchy(StringBuilder sb, FacetMapTargetModel model)
    {
        var indent = "";
        foreach (var containingType in model.ContainingTypes)
        {
            sb.AppendLine($"{indent}partial class {containingType}");
            sb.AppendLine($"{indent}{{");
            indent += "    ";
        }
        return indent;
    }

    private static void CloseContainingTypeHierarchy(StringBuilder sb, FacetMapTargetModel model)
    {
        for (int i = model.ContainingTypes.Length - 1; i >= 0; i--)
        {
            var indent = new string(' ', i * 4);
            sb.AppendLine($"{indent}}}");
        }
    }

    private static string GetSimpleTypeName(string fullyQualifiedName)
    {
        var name = fullyQualifiedName.Replace("global::", "");
        var lastDot = name.LastIndexOf('.');
        return lastDot >= 0 ? name.Substring(lastDot + 1) : name;
    }
}
