using System;

namespace Facet.Tests.TestModels;

// Test models for Flatten attribute

public class Person
{
    public int Id { get; set; }
    public string FirstName { get; set; } = string.Empty;
    public string LastName { get; set; } = string.Empty;
    public DateTime DateOfBirth { get; set; }
    public Address Address { get; set; } = null!;
    public ContactInfo ContactInfo { get; set; } = null!;
}

public class Address
{
    public string Street { get; set; } = string.Empty;
    public string City { get; set; } = string.Empty;
    public string ZipCode { get; set; } = string.Empty;
    public Country Country { get; set; } = null!;
}

public class Country
{
    public string Name { get; set; } = string.Empty;
    public string Code { get; set; } = string.Empty;
}

public class ContactInfo
{
    public string Email { get; set; } = string.Empty;
    public string Phone { get; set; } = string.Empty;
}

// Flattened DTOs

[Flatten(typeof(Person))]
public partial class PersonFlatDto
{
    // All properties generated by source generator
}

[Flatten(typeof(Person), MaxDepth = 2)]
public partial class PersonFlatDepth2Dto
{
    // Limited to 2 levels deep
}

[Flatten(typeof(Person), "ContactInfo")]
public partial class PersonFlatWithoutContactDto
{
    // Excludes ContactInfo properties
}

[Flatten(typeof(Person), "Address.Country")]
public partial class PersonFlatWithoutCountryDto
{
    // Excludes nested Country properties
}

[Flatten(typeof(Person), NamingStrategy = FlattenNamingStrategy.LeafOnly)]
public partial class PersonFlatLeafOnlyDto
{
    // Uses leaf-only naming strategy
}

// Test models for collections
public class Company
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public Address HeadquartersAddress { get; set; } = null!;
    public List<Worker> Workers { get; set; } = new();
}

public class Worker
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public string Title { get; set; } = string.Empty;
    public int CompanyId { get; set; }
}

[Flatten(typeof(Company))]
public partial class CompanyFlatDto
{
    // Collections should be completely ignored - no Count, IsReadOnly, or Worker properties
}

// Test models for nested IDs
public class Order
{
    public int Id { get; set; }
    public DateTime OrderDate { get; set; }
    public int CustomerId { get; set; }
    public Customer Customer { get; set; } = null!;
    public decimal Total { get; set; }
}

public class Customer
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public string Email { get; set; } = string.Empty;
    public int? PreferredAddressId { get; set; }
}

[Flatten(typeof(Order), IgnoreNestedIds = true)]
public partial class OrderFlatDto
{
    // Only Order.Id should be included
    // Customer.Id, Order.CustomerId, and Customer.PreferredAddressId should be excluded
}

[Flatten(typeof(Order), IgnoreNestedIds = false)]
public partial class OrderFlatWithAllIdsDto
{
    // All IDs should be included for comparison
}
