using Facet;

namespace Facet.Tests.TestModels;

/// <summary>
/// Test entities for GenerateDtos integration testing.
/// These will have DTOs generated by the source generator.
/// </summary>

[GenerateDtos(Types = DtoTypes.All, OutputType = OutputType.Class)]
public class TestUser
{
    public int Id { get; set; }
    public string FirstName { get; set; } = string.Empty;
    public string LastName { get; set; } = string.Empty;
    public string Email { get; set; } = string.Empty;
    public string Password { get; set; } = string.Empty;
    public DateTime DateOfBirth { get; set; }
    public bool IsActive { get; set; }
    public DateTime? LastLoginAt { get; set; }
    public DateTime CreatedAt { get; set; }
}

// Dedicated entity for Patch DTO testing
[GenerateDtos(Types = DtoTypes.Patch, OutputType = OutputType.Class)]
public class PatchTestEntity
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public string? Email { get; set; }
    public bool IsActive { get; set; }
    public DateTime? LastLoginAt { get; set; }
    public decimal Price { get; set; }
}

// Uses ExcludeAuditFields = true to automatically exclude audit fields
[GenerateDtos(Types = DtoTypes.Create | DtoTypes.Update | DtoTypes.Response, OutputType = OutputType.Class, ExcludeAuditFields = true)]
public class TestProduct
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public decimal Price { get; set; }
    public bool IsAvailable { get; set; }
    public string InternalNotes { get; set; } = string.Empty;
    public DateTime CreatedAt { get; set; }
    public DateTime UpdatedAt { get; set; }
    public string CreatedBy { get; set; } = string.Empty;
    public string UpdatedBy { get; set; } = string.Empty;
}

// Additional test entities with different configurations

[GenerateDtos(Types = DtoTypes.Response | DtoTypes.Query, OutputType = OutputType.Record)]
public class TestOrder
{
    public Guid Id { get; set; }
    public string OrderNumber { get; set; } = string.Empty;
    public decimal TotalAmount { get; set; }
    public DateTime OrderDate { get; set; }
    public string CustomerEmail { get; set; } = string.Empty;
    public OrderStatus Status { get; set; }
    public string? Notes { get; set; }
}

public enum OrderStatus
{
    Pending,
    Processing,
    Shipped,
    Delivered,
    Cancelled
}

[GenerateDtos(Types = DtoTypes.Response, OutputType = OutputType.Class, ConvertEnumsTo = typeof(string))]
public class TestOrderStringEnumConversion
{
    public int Id { get; set; }
    public OrderStatus Status { get; set; }
    public OrderStatus? PreviousStatus { get; set; }
}

[GenerateDtos(Types = DtoTypes.Response, OutputType = OutputType.Class, ConvertEnumsTo = typeof(int))]
public class TestOrderIntEnumConversion
{
    public int Id { get; set; }
    public OrderStatus Status { get; set; }
    public OrderStatus? PreviousStatus { get; set; }
}

[GenerateDtos(Types = DtoTypes.Create, OutputType = OutputType.Class, ExcludeProperties = new[] { "SecretKey" })]
[GenerateDtos(Types = DtoTypes.Response, OutputType = OutputType.Class, ExcludeProperties = new[] { "SecretKey", "InternalData" })]
public class TestMultiConfigEntity
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public string SecretKey { get; set; } = string.Empty;
    public string InternalData { get; set; } = string.Empty;
    public bool IsPublic { get; set; }
}

[GenerateDtos(Types = DtoTypes.All, OutputType = OutputType.Record, Prefix = "Api", Suffix = "Model")]
public class TestCustomNaming
{
    public int Id { get; set; }
    public string Title { get; set; } = string.Empty;
    public string Content { get; set; } = string.Empty;
    public DateTime PublishedAt { get; set; }
}

// Uses ExcludeAuditFields = true with RecordStruct output
[GenerateDtos(Types = DtoTypes.All, OutputType = OutputType.RecordStruct, ExcludeAuditFields = true)]
public class TestCompactEntity
{
    public int Id { get; set; }
    public string Code { get; set; } = string.Empty;
    public string Value { get; set; } = string.Empty;
    public bool IsEnabled { get; set; }
    public DateTime CreatedAt { get; set; }
    public string CreatedBy { get; set; } = string.Empty;
}

[GenerateDtos(Types = DtoTypes.Response, OutputType = OutputType.Class, IncludeFields = true)]
public class TestEntityWithFields
{
    public int Id;
    public string PublicField = string.Empty;
    public readonly string ReadOnlyField = "readonly"; // Fixed name and made readonly
    public string PropertyField { get; set; } = string.Empty;
    private string PrivateField = "private"; // Should not be included
}

[GenerateDtos(Types = DtoTypes.Create | DtoTypes.Update, OutputType = OutputType.Class)]
public class TestComplexTypes
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public List<string> Tags { get; set; } = new();
    public Dictionary<string, string> Metadata { get; set; } = new();
    public TestNestedType? NestedObject { get; set; }
    public TestNestedType[] ArrayProperty { get; set; } = Array.Empty<TestNestedType>();
}

public class TestNestedType
{
    public string Property1 { get; set; } = string.Empty;
    public int Property2 { get; set; }
}

// Interface output: emits ICreateTestInterfaceEntityRequest / IUpdateTestInterfaceEntityRequest /
// TestInterfaceEntityResponse as interfaces declaring the entity-mapped properties as get-only.
// Useful when you want compile-time enforcement that hand-written DTOs cover all entity fields
// without giving up the DTO's own shape (construction syntax, validation, extra fields).
[GenerateDtos(Types = DtoTypes.Create | DtoTypes.Update | DtoTypes.Response, OutputType = OutputType.Interface)]
public class TestInterfaceEntity
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public string? Description { get; set; }
    public bool IsActive { get; set; }
}

// PartialClass output: emits CreateTestPartialClassEntityRequest / UpdateTestPartialClassEntityRequest /
// TestPartialClassEntityResponse as `public partial class` (not sealed) with get/set properties and the
// same constructors as OutputType.Class — but without projection/ToSource/BackTo. The hand-written
// partial below adds an extra computed property to prove the partial keyword survived generation.
[GenerateDtos(Types = DtoTypes.Create | DtoTypes.Update | DtoTypes.Response, OutputType = OutputType.PartialClass)]
public class TestPartialClassEntity
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public string? Description { get; set; }
    public bool IsActive { get; set; }
}

// Hand-written partial extension — fails to compile if the generated DTOs are NOT emitted as `partial class`.
public partial class UpdateTestPartialClassEntityRequest
{
    public string DisplayLabel => $"{Id}: {Name}";
}

// Both Interface and PartialClass on the same entity: the PartialClass output should declare the
// matching generated interface as a base type, composing into a contract + implementation pair.
[GenerateDtos(Types = DtoTypes.Create | DtoTypes.Update | DtoTypes.Response, OutputType = OutputType.Interface)]
[GenerateDtos(Types = DtoTypes.Create | DtoTypes.Update | DtoTypes.Response, OutputType = OutputType.PartialClass)]
public class TestPartialAndInterfaceEntity
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public bool IsActive { get; set; }
}

// PartialClass intentionally NOT sealed: a hand-written derived type should compile.
// This exercises the GlobalSoftware/LocalSoftware-style inheritance scenario.
public class DerivedFromGeneratedPartial : UpdateTestPartialClassEntityRequest
{
    public string DerivedOnly { get; set; } = string.Empty;
}
