using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;

namespace Facet.Generators.Shared;

/// <summary>
/// Shared utility methods for Facet source generators.
/// </summary>
internal static class GeneratorUtilities
{
    /// <summary>
    /// The global namespace prefix used in fully qualified type names.
    /// </summary>
    public const string GlobalPrefix = "global::";

    /// <summary>
    /// Strips the global:: prefix from a type name if present.
    /// </summary>
    public static string StripGlobalPrefix(string typeName)
    {
        return typeName.StartsWith(GlobalPrefix)
            ? typeName.Substring(GlobalPrefix.Length)
            : typeName;
    }

    private static readonly SymbolDisplayFormat NullabilityFormat = new SymbolDisplayFormat(
        globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Included,
        typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
        genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters | SymbolDisplayGenericsOptions.IncludeVariance,
        memberOptions: SymbolDisplayMemberOptions.None,
        delegateStyle: SymbolDisplayDelegateStyle.NameAndSignature,
        extensionMethodStyle: SymbolDisplayExtensionMethodStyle.Default,
        parameterOptions: SymbolDisplayParameterOptions.None,
        propertyStyle: SymbolDisplayPropertyStyle.NameOnly,
        localOptions: SymbolDisplayLocalOptions.None,
        kindOptions: SymbolDisplayKindOptions.None,
        miscellaneousOptions: SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers |
                             SymbolDisplayMiscellaneousOptions.UseSpecialTypes |
                             SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    /// <summary>
    /// Gets the type name with proper nullability information preserved.
    /// </summary>
    /// <param name="typeSymbol">The type symbol to get the name from.</param>
    /// <returns>A fully qualified type name with nullability annotations.</returns>
    public static string GetTypeNameWithNullability(ITypeSymbol typeSymbol)
        => typeSymbol.ToDisplayString(NullabilityFormat);

    /// <summary>
    /// Returns true if the property symbol is a partial implementing declaration (C# 13+),
    /// i.e., it has the <c>partial</c> modifier AND its accessors have bodies.
    /// Implementing declarations are generated by other source generators (e.g., MVVM toolkit)
    /// and should be skipped in favour of the user-authored defining declaration.
    /// </summary>
    private static bool IsPartialImplementingDeclaration(IPropertySymbol property)
    {
        var sawPartialDeclaration = false;

        foreach (var syntaxRef in property.DeclaringSyntaxReferences)
        {
            if (syntaxRef.GetSyntax() is PropertyDeclarationSyntax propSyntax)
            {
                var hasPartial = propSyntax.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword));
                if (!hasPartial)
                    continue;

                sawPartialDeclaration = true;

                var hasAccessorBody = propSyntax.AccessorList?.Accessors
                    .Any(a => a.Body != null || a.ExpressionBody != null) == true;

                if (!hasAccessorBody)
                    return false;
            }
        }

        return sawPartialDeclaration;
    }

    /// <summary>
    /// Gets all members from the inheritance hierarchy, starting from the most derived type
    /// and walking up to the base types. This ensures that overridden members are preferred.
    /// </summary>
    /// <param name="type">The type symbol to get members from.</param>
    /// <returns>An enumerable of tuples containing the symbol, init-only flag, and required flag.</returns>
    public static IEnumerable<(ISymbol Symbol, bool IsInitOnly, bool IsRequired)> GetAllMembersWithModifiers(INamedTypeSymbol type)
    {
        var visited = new HashSet<string>();
        var current = type;

        while (current != null)
        {
            foreach (var member in current.GetMembers())
            {
                if (member.DeclaredAccessibility == Accessibility.Public &&
                    !member.IsStatic &&
                    !visited.Contains(member.Name))
                {
                    if (member is IPropertySymbol prop)
                    {
                        // Skip partial implementing declarations emitted for attributes like [ObservableProperty].
                        if (IsPartialImplementingDeclaration(prop)) continue;

                        visited.Add(member.Name);
                        var isInitOnly = prop.SetMethod?.IsInitOnly == true;
                        var isRequired = prop.IsRequired;
                        yield return (prop, isInitOnly, isRequired);
                    }
                    else if (member is IFieldSymbol field)
                    {
                        visited.Add(member.Name);
                        var isRequired = field.IsRequired;
                        yield return (field, false, isRequired);
                    }
                }
            }

            current = current.BaseType;

            if (current?.SpecialType == SpecialType.System_Object)
                break;
        }
    }

    /// <summary>
    /// Determines if a type is a value type based on its name.
    /// </summary>
    /// <param name="typeName">The fully qualified or simple type name.</param>
    /// <returns>True if the type is a value type; otherwise, false.</returns>
    public static bool IsValueType(string typeName)
    {
        return typeName switch
        {
            "bool" or "System.Boolean" => true,
            "byte" or "System.Byte" => true,
            "sbyte" or "System.SByte" => true,
            "char" or "System.Char" => true,
            "decimal" or "System.Decimal" => true,
            "double" or "System.Double" => true,
            "float" or "System.Single" => true,
            "int" or "System.Int32" => true,
            "uint" or "System.UInt32" => true,
            "long" or "System.Int64" => true,
            "ulong" or "System.UInt64" => true,
            "short" or "System.Int16" => true,
            "ushort" or "System.UInt16" => true,
            "System.DateTime" => true,
            "System.DateTimeOffset" => true,
            "System.TimeSpan" => true,
            "System.Guid" => true,
            _ when typeName.StartsWith("System.Enum") => true,
            _ when typeName.EndsWith("Enum") => true,  
            _ => false
        };
    }

    /// <summary>
    /// Makes a type nullable by appending a '?' suffix if it's not already nullable.
    /// </summary>
    /// <param name="typeName">The type name to make nullable.</param>
    /// <returns>The nullable version of the type name.</returns>
    public static string MakeNullable(string typeName)
    {
        if (typeName.EndsWith("?") || typeName.StartsWith("System.Nullable<"))
            return typeName;

        return typeName + "?";
    }

    /// <summary>
    /// Gets the appropriate default value expression for a given type name.
    /// Used for parameterless constructor generation and required field initialization.
    /// </summary>
    /// <param name="typeName">The fully qualified or simple type name.</param>
    /// <returns>A C# expression string representing the default value.</returns>
    public static string GetDefaultValueForType(string typeName)
    {
        var cleanTypeName = StripGlobalPrefix(typeName);

        if (cleanTypeName.EndsWith("?"))
        {
            return "null";
        }

        if (cleanTypeName.StartsWith("System.Nullable<"))
        {
            return "null";
        }

        return cleanTypeName switch
        {
            "string" or "System.String" => "string.Empty",

            "int" or "System.Int32" => "0",
            "long" or "System.Int64" => "0L",
            "short" or "System.Int16" => "(short)0",
            "byte" or "System.Byte" => "(byte)0",
            "sbyte" or "System.SByte" => "(sbyte)0",
            "uint" or "System.UInt32" => "0U",
            "ulong" or "System.UInt64" => "0UL",
            "ushort" or "System.UInt16" => "(ushort)0",
            "float" or "System.Single" => "0.0f",
            "double" or "System.Double" => "0.0",
            "decimal" or "System.Decimal" => "0.0m",

            "bool" or "System.Boolean" => "false",
            "char" or "System.Char" => "'\\0'",
            "System.DateTime" => "default(System.DateTime)",
            "System.DateTimeOffset" => "default(System.DateTimeOffset)",
            "System.TimeSpan" => "default(System.TimeSpan)",
            "System.Guid" => "default(System.Guid)",

            _ when cleanTypeName.StartsWith("System.Collections.Generic.List<") => $"new {cleanTypeName}()",
            _ when cleanTypeName.StartsWith("System.Collections.Generic.IList<") =>
                $"new System.Collections.Generic.List<{cleanTypeName.Substring("System.Collections.Generic.IList<".Length).TrimEnd('>')}>()",
            _ when cleanTypeName.StartsWith("List<") => $"new {cleanTypeName}()",
            _ when cleanTypeName.StartsWith("IList<") =>
                $"new List<{cleanTypeName.Substring("IList<".Length).TrimEnd('>')}>()",

            _ when cleanTypeName.StartsWith("System.Collections.Immutable.ImmutableArray<") => $"default({cleanTypeName})",
            _ when cleanTypeName.StartsWith("System.Collections.Immutable.ImmutableList<") => $"{cleanTypeName}.Empty",
            _ when cleanTypeName.StartsWith("System.Collections.Immutable.ImmutableHashSet<") => $"{cleanTypeName}.Empty",
            _ when cleanTypeName.StartsWith("System.Collections.Immutable.ImmutableSortedSet<") => $"{cleanTypeName}.Empty",
            _ when cleanTypeName.StartsWith("System.Collections.Immutable.ImmutableQueue<") => $"{cleanTypeName}.Empty",
            _ when cleanTypeName.StartsWith("System.Collections.Immutable.ImmutableStack<") => $"{cleanTypeName}.Empty",
            _ when cleanTypeName.StartsWith("System.Collections.Immutable.IImmutableList<") =>
                $"System.Collections.Immutable.ImmutableList<{cleanTypeName.Substring("System.Collections.Immutable.IImmutableList<".Length).TrimEnd('>')}>.Empty",
            _ when cleanTypeName.StartsWith("System.Collections.Immutable.IImmutableSet<") =>
                $"System.Collections.Immutable.ImmutableHashSet<{cleanTypeName.Substring("System.Collections.Immutable.IImmutableSet<".Length).TrimEnd('>')}>.Empty",
            _ when cleanTypeName.StartsWith("System.Collections.Immutable.IImmutableQueue<") =>
                $"System.Collections.Immutable.ImmutableQueue<{cleanTypeName.Substring("System.Collections.Immutable.IImmutableQueue<".Length).TrimEnd('>')}>.Empty",
            _ when cleanTypeName.StartsWith("System.Collections.Immutable.IImmutableStack<") =>
                $"System.Collections.Immutable.ImmutableStack<{cleanTypeName.Substring("System.Collections.Immutable.IImmutableStack<".Length).TrimEnd('>')}>.Empty",

            _ when IsValueType(cleanTypeName) => $"default({cleanTypeName})",
            _ => "null" 
        };
    }

    /// <summary>
    /// Gets the default value expression for a given type, using semantic type information
    /// to correctly handle custom value types (structs) that aren't in the known type list.
    /// </summary>
    /// <param name="typeName">The fully qualified or simple type name.</param>
    /// <param name="isValueType">Whether the type is a value type (from semantic analysis).</param>
    /// <returns>A C# expression string representing the default value.</returns>
    public static string GetDefaultValueForType(string typeName, bool isValueType)
    {
        var result = GetDefaultValueForType(typeName);

        if (result == "null" && isValueType)
        {
            var cleanTypeName = StripGlobalPrefix(typeName);
            return $"default({cleanTypeName})";
        }

        return result;
    }

    /// <summary>
    /// Gets a default value suitable for parameterless constructor initialization.
    /// Similar to GetDefaultValueForType but with slight variations for constructor contexts.
    /// </summary>
    /// <param name="typeName">The type name.</param>
    /// <returns>A C# expression string representing the default value.</returns>
    public static string GetDefaultValue(string typeName)
    {
        if (typeName.EndsWith("?"))
        {
            return $"({typeName})null";
        }

        return typeName switch
        {
            "bool" => "false",
            "byte" => "0",
            "sbyte" => "0",
            "short" => "0",
            "ushort" => "0",
            "int" => "0",
            "uint" => "0",
            "long" => "0",
            "ulong" => "0",
            "float" => "0f",
            "double" => "0d",
            "decimal" => "0m",
            "char" => "'\\0'",
            "string" => "string.Empty",
            var t when t.StartsWith("System.DateTime") => "default",
            var t when t.StartsWith("System.DateTimeOffset") => "default",
            var t when t.StartsWith("System.TimeSpan") => "default",
            var t when t.StartsWith("System.Guid") => "default",
            
            var t when IsValueType(t) => $"default({typeName})",
            
            _ => $"default({typeName})!"
        };
    }

    /// <summary>
    /// Attempts to extract the element type from a collection type.
    /// Uses a hybrid approach: exact type matching for known concrete types (to preserve specific implementations),
    /// then falls back to interface-based detection (to automatically support custom collection types).
    /// This makes the generator extensible to any custom collection type implementing standard interfaces.
    /// </summary>
    /// <param name="typeSymbol">The type symbol to analyze.</param>
    /// <param name="elementType">The extracted element type symbol if successful.</param>
    /// <param name="collectionWrapper">The collection type wrapper (e.g., "List", "ICollection", "IReadOnlyList", "ImmutableList", "array").</param>
    /// <returns>True if the type is a collection; otherwise, false.</returns>
    public static bool TryGetCollectionElementType(ITypeSymbol typeSymbol, out ITypeSymbol? elementType, out string? collectionWrapper)
    {
        elementType = null;
        collectionWrapper = null;

        if (typeSymbol is IArrayTypeSymbol arrayType)
        {
            elementType = arrayType.ElementType;
            collectionWrapper = "array";
            return true;
        }

        if (typeSymbol is INamedTypeSymbol namedType && namedType.IsGenericType)
        {
            var typeDefinition = namedType.OriginalDefinition.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            if (typeDefinition == "global::System.Collections.Generic.IList<T>")
            {
                elementType = namedType.TypeArguments[0];
                collectionWrapper = "IList";
                return true;
            }

            if (typeDefinition == "global::System.Collections.Generic.ICollection<T>")
            {
                elementType = namedType.TypeArguments[0];
                collectionWrapper = "ICollection";
                return true;
            }

            if (typeDefinition == "global::System.Collections.Generic.IEnumerable<T>")
            {
                elementType = namedType.TypeArguments[0];
                collectionWrapper = "IEnumerable";
                return true;
            }

            if (typeDefinition == "global::System.Collections.Generic.IReadOnlyList<T>")
            {
                elementType = namedType.TypeArguments[0];
                collectionWrapper = "IReadOnlyList";
                return true;
            }

            if (typeDefinition == "global::System.Collections.Generic.IReadOnlyCollection<T>")
            {
                elementType = namedType.TypeArguments[0];
                collectionWrapper = "IReadOnlyCollection";
                return true;
            }

            if (typeDefinition == "global::System.Collections.Immutable.IImmutableList<T>")
            {
                elementType = namedType.TypeArguments[0];
                collectionWrapper = "IImmutableList";
                return true;
            }

            if (typeDefinition == "global::System.Collections.Immutable.IImmutableSet<T>")
            {
                elementType = namedType.TypeArguments[0];
                collectionWrapper = "IImmutableSet";
                return true;
            }

            if (typeDefinition == "global::System.Collections.Immutable.IImmutableQueue<T>")
            {
                elementType = namedType.TypeArguments[0];
                collectionWrapper = "IImmutableQueue";
                return true;
            }

            if (typeDefinition == "global::System.Collections.Immutable.IImmutableStack<T>")
            {
                elementType = namedType.TypeArguments[0];
                collectionWrapper = "IImmutableStack";
                return true;
            }

            if (typeDefinition == "global::System.Collections.Generic.List<T>")
            {
                elementType = namedType.TypeArguments[0];
                collectionWrapper = "List";
                return true;
            }

            if (typeDefinition == "global::System.Collections.ObjectModel.Collection<T>")
            {
                elementType = namedType.TypeArguments[0];
                collectionWrapper = "Collection";
                return true;
            }

            if (typeDefinition == "global::System.Collections.Immutable.ImmutableArray<T>")
            {
                elementType = namedType.TypeArguments[0];
                collectionWrapper = "ImmutableArray";
                return true;
            }

            if (typeDefinition == "global::System.Collections.Immutable.ImmutableList<T>")
            {
                elementType = namedType.TypeArguments[0];
                collectionWrapper = "ImmutableList";
                return true;
            }

            if (typeDefinition == "global::System.Collections.Immutable.ImmutableHashSet<T>")
            {
                elementType = namedType.TypeArguments[0];
                collectionWrapper = "ImmutableHashSet";
                return true;
            }

            if (typeDefinition == "global::System.Collections.Immutable.ImmutableSortedSet<T>")
            {
                elementType = namedType.TypeArguments[0];
                collectionWrapper = "ImmutableSortedSet";
                return true;
            }

            if (typeDefinition == "global::System.Collections.Immutable.ImmutableQueue<T>")
            {
                elementType = namedType.TypeArguments[0];
                collectionWrapper = "ImmutableQueue";
                return true;
            }

            if (typeDefinition == "global::System.Collections.Immutable.ImmutableStack<T>")
            {
                elementType = namedType.TypeArguments[0];
                collectionWrapper = "ImmutableStack";
                return true;
            }

            var interfaces = namedType.AllInterfaces;

            if (ImplementsGenericInterface(interfaces, "System.Collections.Generic.IReadOnlyList<T>"))
            {
                elementType = namedType.TypeArguments[0];
                collectionWrapper = "IReadOnlyList";
                return true;
            }

            if (ImplementsGenericInterface(interfaces, "System.Collections.Generic.IReadOnlyCollection<T>"))
            {
                elementType = namedType.TypeArguments[0];
                collectionWrapper = "IReadOnlyCollection";
                return true;
            }

            if (ImplementsGenericInterface(interfaces, "System.Collections.Generic.IList<T>"))
            {
                elementType = namedType.TypeArguments[0];
                collectionWrapper = "IList";
                return true;
            }

            if (ImplementsGenericInterface(interfaces, "System.Collections.Generic.ICollection<T>"))
            {
                elementType = namedType.TypeArguments[0];
                collectionWrapper = "ICollection";
                return true;
            }

            if (ImplementsGenericInterface(interfaces, "System.Collections.Generic.IEnumerable<T>"))
            {
                elementType = namedType.TypeArguments[0];
                collectionWrapper = "IEnumerable";
                return true;
            }
        }

        return false;
    }

    /// <summary>
    /// Checks if a type implements a specific generic interface.
    /// </summary>
    /// <param name="interfaces">The collection of interfaces implemented by the type.</param>
    /// <param name="interfaceName">The fully qualified generic interface name (e.g., "System.Collections.Generic.IList&lt;T&gt;").</param>
    /// <returns>True if the type implements the specified interface; otherwise, false.</returns>
    private static bool ImplementsGenericInterface(ImmutableArray<INamedTypeSymbol> interfaces, string interfaceName)
    {
        return interfaces.Any(i =>
            i.IsGenericType &&
            i.OriginalDefinition.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == $"global::{interfaceName}");
    }

    /// <summary>
    /// Determines if a type symbol represents a nested type (a type declared within another type).
    /// Unwraps nullable annotations and collection element types to check the underlying type.
    /// </summary>
    /// <param name="typeSymbol">The type symbol to check.</param>
    /// <returns>True if the underlying type is nested within another type; otherwise, false.</returns>
    public static bool IsNestedType(ITypeSymbol typeSymbol)
    {
        if (TryGetCollectionElementType(typeSymbol, out var elementType, out _) && elementType != null)
        {
            return elementType.ContainingType != null;
        }

        if (typeSymbol is INamedTypeSymbol namedType &&
            namedType.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T)
        {
            return namedType.TypeArguments[0].ContainingType != null;
        }

        return typeSymbol.ContainingType != null;
    }

    /// <summary>
    /// Wraps an element type name in the appropriate collection type.
    /// </summary>
    /// <param name="elementTypeName">The fully qualified element type name.</param>
    /// <param name="collectionWrapper">The collection wrapper type ("List", "ICollection", "IList", "IEnumerable", "IReadOnlyList", "IReadOnlyCollection", "Collection", "ImmutableArray", "ImmutableList", "IImmutableList", etc., "array").</param>
    /// <returns>The fully qualified collection type name.</returns>
    public static string WrapInCollectionType(string elementTypeName, string collectionWrapper)
    {
        return collectionWrapper switch
        {
            "List" => $"global::System.Collections.Generic.List<{elementTypeName}>",
            "ICollection" => $"global::System.Collections.Generic.ICollection<{elementTypeName}>",
            "IList" => $"global::System.Collections.Generic.IList<{elementTypeName}>",
            "IEnumerable" => $"global::System.Collections.Generic.IEnumerable<{elementTypeName}>",
            "IReadOnlyList" => $"global::System.Collections.Generic.IReadOnlyList<{elementTypeName}>",
            "IReadOnlyCollection" => $"global::System.Collections.Generic.IReadOnlyCollection<{elementTypeName}>",
            "Collection" => $"global::System.Collections.ObjectModel.Collection<{elementTypeName}>",
            "ImmutableArray" => $"global::System.Collections.Immutable.ImmutableArray<{elementTypeName}>",
            "ImmutableList" => $"global::System.Collections.Immutable.ImmutableList<{elementTypeName}>",
            "ImmutableHashSet" => $"global::System.Collections.Immutable.ImmutableHashSet<{elementTypeName}>",
            "ImmutableSortedSet" => $"global::System.Collections.Immutable.ImmutableSortedSet<{elementTypeName}>",
            "ImmutableQueue" => $"global::System.Collections.Immutable.ImmutableQueue<{elementTypeName}>",
            "ImmutableStack" => $"global::System.Collections.Immutable.ImmutableStack<{elementTypeName}>",
            "IImmutableList" => $"global::System.Collections.Immutable.IImmutableList<{elementTypeName}>",
            "IImmutableSet" => $"global::System.Collections.Immutable.IImmutableSet<{elementTypeName}>",
            "IImmutableQueue" => $"global::System.Collections.Immutable.IImmutableQueue<{elementTypeName}>",
            "IImmutableStack" => $"global::System.Collections.Immutable.IImmutableStack<{elementTypeName}>",
            "array" => $"{elementTypeName}[]",
            _ => elementTypeName
        };
    }
}
