using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Facet.Extensions.EFCore.Generators.Emission;

/// <summary>
/// Emits shape interfaces that define the base scalar properties of entities.
/// </summary>
internal static class ShapeInterfacesEmitter
{
    public static void Emit(SourceProductionContext context, ModelRoot efModel, ImmutableArray<FacetDtoInfo> facetDtos)
    {
        foreach (var contextModel in efModel.Contexts)
        {
            foreach (var entity in contextModel.Entities)
            {
                // Find matching DTO
                var matchingDto = facetDtos.FirstOrDefault(dto => 
                    string.Equals(dto.EntityTypeName, entity.Clr, System.StringComparison.OrdinalIgnoreCase));

                if (matchingDto == null)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        Diagnostics.DtoNotFound,
                        Location.None,
                        "No DTO found",
                        entity.Clr ?? entity.Name));
                    continue;
                }

                GenerateShapeInterface(context, entity, matchingDto);
            }
        }
    }

    private static void GenerateShapeInterface(SourceProductionContext context, EntityModel entity, FacetDtoInfo dtoInfo)
    {
        var entityName = GetSimpleTypeName(entity.Clr ?? entity.Name);
        var interfaceName = $"I{entityName}Shape";
        
        var sb = new StringBuilder();
        
        // Generate file header
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {dtoInfo.DtoNamespace};");
        sb.AppendLine();
        
        // Generate shape interface
        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// Defines the shape of {entityName} with scalar properties only.");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"public interface {interfaceName}");
        sb.AppendLine("{");
        
        // Note: In a full implementation, we'd need to inspect the actual DTO properties
        // For now, we'll generate a placeholder that assumes common properties
        sb.AppendLine("    // Scalar properties from the DTO would be defined here");
        sb.AppendLine("    // This would require analyzing the actual DTO type's properties");
        
        sb.AppendLine("}");

        var sourceText = SourceText.From(sb.ToString(), System.Text.Encoding.UTF8);
        context.AddSource($"{interfaceName}.g.cs", sourceText);
    }

    private static string GetSimpleTypeName(string fullTypeName)
    {
        var lastDot = fullTypeName.LastIndexOf('.');
        return lastDot >= 0 ? fullTypeName.Substring(lastDot + 1) : fullTypeName;
    }
}