# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: build
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "master"
      - "develop"
  pull_request:
    branches:
      - "*"

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace }}/nuget

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Pack NuGet Packages
        run: dotnet pack --configuration Release --no-build --output ${{ env.NuGetDirectory }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          if-no-files-found: error
          retention-days: 7
          path: ${{ env.NuGetDirectory }}/*.nupkg

  test-console:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build test console
        run: dotnet build test/Facet.TestConsole --configuration Release

      - name: Run test console
        run: |
          cd test/Facet.TestConsole
          timeout 30s dotnet run --configuration Release --no-build || true