# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: build
run-name: '[Build] ${{ github.event.head_commit.message || github.event.pull_request.title || github.ref_name }}'
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "master"
      - "develop"
  pull_request:
    branches:
      - "*"

permissions:
  contents: read
  checks: write
  pull-requests: write

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace }}/nuget

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --configuration Release --no-restore

      - name: Pack NuGet Packages
        run: dotnet pack --configuration Release --no-build --output ${{ env.NuGetDirectory }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          if-no-files-found: error
          retention-days: 7
          path: ${{ env.NuGetDirectory }}/*.nupkg