using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace Facet.Generators.Fluent;

/// <summary>
/// Emits the fluent query surface for one entity: shape interfaces (scalar-only, get-only),
/// covariant capability interfaces per navigation, nominal composed interfaces per used nav
/// combination, ONE concrete shape class per entity (settable, implementing every interface
/// with concrete type args — variance supplies all interface-typed views), one selector
/// expression per used state, chain-marker types for nested lambdas, the query struct with
/// terminals, and the entry-point/transition extension methods.
/// Everything is fully qualified (no usings), internal, and lands in the entity's own
/// namespace — one generated file per entity, with no cross-file ordering concerns.
/// </summary>
internal sealed class FluentEmitter
{
    private readonly ImmutableDictionary<string, EntityPlan> _plans;

    public FluentEmitter(ImmutableDictionary<string, EntityPlan> plans)
    {
        _plans = plans;
    }

    private FluentEntityModel Target(FluentNav nav) => _plans[nav.TargetClrName].Model;

    // ---- naming ---------------------------------------------------------------------

    private static string Qualified(FluentEntityModel model, string typeName)
        => model.Namespace.Length == 0 ? "global::" + typeName : "global::" + model.Namespace + "." + typeName;

    private static string ShapeInterfaceName(FluentEntityModel m) => "I" + m.SimpleName + "Shape";
    private static string CapabilityName(FluentEntityModel m, string nav) => "I" + m.SimpleName + "With" + nav;
    private static string ComposedName(FluentEntityModel m, ImmutableArray<string> navs) => "I" + m.SimpleName + "With" + string.Join("And", navs);
    private static string ConcreteName(FluentEntityModel m) => m.SimpleName + "FacetShape";
    private static string SelectorsName(FluentEntityModel m) => m.SimpleName + "FacetSelectors";
    private static string QueryName(FluentEntityModel m) => "Facet" + m.SimpleName + "Query";
    private static string ChainsName(FluentEntityModel m) => "Facet" + m.SimpleName + "QueryChains";
    private static string MarkerName(FluentEntityModel m, ImmutableArray<ChainNode> state)
        => state.Length == 0
            ? m.SimpleName + "FacetChain"
            : m.SimpleName + "FacetChain_" + ChainCanon.Identifier(state);

    private static string SelectorProperty(ImmutableArray<ChainNode> state)
        => state.Length == 0 ? "Bare" : "With_" + ChainCanon.Identifier(state);

    /// <summary>The interface-typed view of a state: the query's TShape for that state.</summary>
    private string InterfaceType(FluentEntityModel m, ImmutableArray<ChainNode> state)
    {
        if (state.Length == 0) return Qualified(m, ShapeInterfaceName(m));

        var sorted = ChainCanon.Sort(state);
        var args = string.Join(", ", sorted.Select(node => ShapeArg(m, node)));
        var name = sorted.Length == 1
            ? CapabilityName(m, sorted[0].Nav)
            : ComposedName(m, sorted.Select(n => n.Nav).ToImmutableArray());
        return Qualified(m, name) + "<" + args + ">";
    }

    private string ShapeArg(FluentEntityModel m, ChainNode node)
    {
        var target = Target(m.FindNav(node.Nav)!);
        return InterfaceType(target, node.Children);
    }

    // ---- per-entity file ------------------------------------------------------------

    public string EmitEntity(EntityPlan plan)
    {
        var m = plan.Model;
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        // Selectors project every mapped member verbatim, including [Obsolete] ones — the
        // model still maps them, so dropping them would mis-shape the DTO. Suppress the
        // obsolete-usage warnings inside generated code only; consumers with
        // TreatWarningsAsErrors must not fail on members they never wrote.
        sb.AppendLine("#pragma warning disable CS0612, CS0618");
        sb.AppendLine();
        if (m.Namespace.Length > 0)
        {
            sb.Append("namespace ").Append(m.Namespace).AppendLine(";");
            sb.AppendLine();
        }

        EmitShapeInterface(sb, m);
        EmitCapabilityInterfaces(sb, m);
        EmitComposedInterfaces(sb, plan);
        EmitConcreteClass(sb, plan);
        EmitSelectors(sb, plan);
        EmitQueryStruct(sb, m);
        EmitChains(sb, plan);
        EmitMarkers(sb, plan);

        return sb.ToString();
    }

    private static void EmitShapeInterface(StringBuilder sb, FluentEntityModel m)
    {
        sb.Append("/// <summary>Scalar shape of <see cref=\"").Append(m.GlobalName)
            .AppendLine("\"/>: exactly what the EF model maps as data.</summary>");
        sb.Append("internal interface ").AppendLine(ShapeInterfaceName(m));
        sb.AppendLine("{");
        foreach (var member in m.Members)
        {
            sb.Append("    ").Append(member.TypeDisplay).Append(' ').Append(member.Name).AppendLine(" { get; }");
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    private void EmitCapabilityInterfaces(StringBuilder sb, FluentEntityModel m)
    {
        foreach (var nav in m.Navs)
        {
            var typeParam = "T" + nav.Name;
            sb.Append("/// <summary>").Append(ShapeInterfaceName(m)).Append(" plus the included <c>")
                .Append(nav.Name).AppendLine("</c> navigation, covariant in its shape.</summary>");
            sb.Append("internal interface ").Append(CapabilityName(m, nav.Name))
                .Append("<out ").Append(typeParam).Append("> : ").Append(ShapeInterfaceName(m));
            if (!nav.IsCollection) sb.Append(" where ").Append(typeParam).Append(" : class");
            sb.AppendLine();
            sb.AppendLine("{");
            sb.Append("    ");
            if (nav.IsCollection)
            {
                sb.Append("global::System.Collections.Generic.IReadOnlyList<").Append(typeParam).Append('>');
            }
            else
            {
                sb.Append(typeParam);
                if (nav.IsOptional) sb.Append('?');
            }

            sb.Append(' ').Append(nav.Name).AppendLine(" { get; }");
            sb.AppendLine("}");
            sb.AppendLine();
        }
    }

    private void EmitComposedInterfaces(StringBuilder sb, EntityPlan plan)
    {
        var m = plan.Model;
        foreach (var navs in plan.ComposedSets.Values.OrderBy(v => string.Join(",", v), StringComparer.Ordinal))
        {
            var typeParams = navs.Select(n => "T" + n).ToArray();
            sb.AppendLine("/// <summary>Nominal intersection of the capability interfaces for this navigation combination (C# has no intersection types).</summary>");
            sb.Append("internal interface ").Append(ComposedName(m, navs))
                .Append("<").Append(string.Join(", ", typeParams.Select(p => "out " + p))).Append("> :");
            sb.AppendLine();
            for (var i = 0; i < navs.Length; i++)
            {
                sb.Append("    ").Append(CapabilityName(m, navs[i])).Append('<').Append(typeParams[i]).Append('>')
                    .AppendLine(i < navs.Length - 1 ? "," : string.Empty);
            }

            foreach (var nav in navs)
            {
                if (m.FindNav(nav) is { IsCollection: false })
                {
                    sb.Append("    where T").Append(nav).AppendLine(" : class");
                }
            }

            sb.AppendLine("{");
            sb.AppendLine("}");
            sb.AppendLine();
        }
    }

    private void EmitConcreteClass(StringBuilder sb, EntityPlan plan)
    {
        var m = plan.Model;
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// The single materialization target for every chain. Navigations a chain did not");
        sb.AppendLine("/// include stay null/empty at runtime but are unreachable through that chain's");
        sb.AppendLine("/// interface view — downcasting a shape to this class is unsupported.");
        sb.AppendLine("/// </summary>");
        sb.Append("internal sealed class ").Append(ConcreteName(m)).Append(" :");
        sb.AppendLine();
        sb.Append("    ").Append(ShapeInterfaceName(m));
        foreach (var nav in m.Navs)
        {
            sb.AppendLine(",");
            sb.Append("    ").Append(CapabilityName(m, nav.Name)).Append('<')
                .Append(Qualified(Target(nav), ConcreteName(Target(nav)))).Append('>');
        }

        foreach (var navs in plan.ComposedSets.Values.OrderBy(v => string.Join(",", v), StringComparer.Ordinal))
        {
            sb.AppendLine(",");
            var args = navs.Select(n => Qualified(Target(m.FindNav(n)!), ConcreteName(Target(m.FindNav(n)!))));
            sb.Append("    ").Append(ComposedName(m, navs)).Append('<').Append(string.Join(", ", args)).Append('>');
        }

        sb.AppendLine();
        sb.AppendLine("{");
        foreach (var member in m.Members)
        {
            sb.Append("    public ").Append(member.TypeDisplay).Append(' ').Append(member.Name).Append(" { get; set; }");
            sb.AppendLine(NeedsNullForgiving(member.TypeDisplay) ? " = default!;" : string.Empty);
        }

        foreach (var nav in m.Navs)
        {
            var targetConcrete = Qualified(Target(nav), ConcreteName(Target(nav)));
            if (nav.IsCollection)
            {
                sb.Append("    public global::System.Collections.Generic.IReadOnlyList<").Append(targetConcrete)
                    .Append("> ").Append(nav.Name).Append(" { get; set; } = global::System.Array.Empty<")
                    .Append(targetConcrete).AppendLine(">();");
            }
            else if (nav.IsOptional)
            {
                sb.Append("    public ").Append(targetConcrete).Append("? ").Append(nav.Name).AppendLine(" { get; set; }");
            }
            else
            {
                sb.Append("    public ").Append(targetConcrete).Append(' ').Append(nav.Name).AppendLine(" { get; set; } = null!;");
            }
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    /// <summary>Reference-typed members without a nullable annotation need a null-forgiving initializer.</summary>
    private static bool NeedsNullForgiving(string typeDisplay)
        => !typeDisplay.EndsWith("?", StringComparison.Ordinal)
            && !IsValueLike(typeDisplay);

    private static bool IsValueLike(string typeDisplay)
    {
        // Value types never need an initializer. This recognizes the common keywords and
        // System value types; unrecognized types get "default!", which is harmless for
        // value types (default! == default) and correct for reference types.
        switch (typeDisplay)
        {
            case "int": case "long": case "short": case "byte": case "sbyte":
            case "uint": case "ulong": case "ushort": case "bool": case "char":
            case "float": case "double": case "decimal":
                return true;
            default:
                return typeDisplay.StartsWith("global::System.DateTime", StringComparison.Ordinal)
                    || typeDisplay.StartsWith("global::System.DateOnly", StringComparison.Ordinal)
                    || typeDisplay.StartsWith("global::System.TimeOnly", StringComparison.Ordinal)
                    || typeDisplay.StartsWith("global::System.TimeSpan", StringComparison.Ordinal)
                    || typeDisplay.StartsWith("global::System.Guid", StringComparison.Ordinal);
        }
    }

    private void EmitSelectors(StringBuilder sb, EntityPlan plan)
    {
        var m = plan.Model;
        sb.Append("internal static class ").AppendLine(SelectorsName(m));
        sb.AppendLine("{");
        var first = true;
        foreach (var state in plan.States.OrderBy(s => s.Key, StringComparer.Ordinal))
        {
            if (!first) sb.AppendLine();
            first = false;

            sb.Append("    public static global::System.Linq.Expressions.Expression<global::System.Func<")
                .Append(m.GlobalName).Append(", ").Append(Qualified(m, ConcreteName(m))).Append(">> ")
                .Append(SelectorProperty(state.Value)).AppendLine(" { get; } =");
            sb.Append("        e => ");
            EmitShapeInit(sb, m, state.Value, "e", indent: 8);
            sb.AppendLine(";");
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    private void EmitShapeInit(StringBuilder sb, FluentEntityModel m, ImmutableArray<ChainNode> state, string source, int indent)
    {
        var pad = new string(' ', indent);
        sb.Append("new ").Append(Qualified(m, ConcreteName(m))).AppendLine();
        sb.Append(pad).AppendLine("{");
        var memberPad = pad + "    ";
        foreach (var member in m.Members)
        {
            sb.Append(memberPad).Append(member.Name).Append(" = ").Append(source).Append('.').Append(member.Name).AppendLine(",");
        }

        foreach (var node in ChainCanon.Sort(state))
        {
            var nav = m.FindNav(node.Nav)!;
            var target = Target(nav);
            sb.Append(memberPad).Append(nav.Name).Append(" = ");
            if (nav.IsCollection)
            {
                var item = "v" + indent;
                sb.Append("global::System.Linq.Enumerable.ToList(global::System.Linq.Enumerable.Select(")
                    .Append(source).Append('.').Append(nav.Name).Append("!, ").Append(item).Append(" => ");
                EmitShapeInit(sb, target, node.Children, item, indent + 4);
                sb.AppendLine(")),");
            }
            else if (nav.IsOptional)
            {
                sb.Append(source).Append('.').Append(nav.Name).Append(" == null ? null : ");
                EmitShapeInit(sb, target, node.Children, source + "." + nav.Name + "!", indent + 4);
                sb.AppendLine(",");
            }
            else
            {
                EmitShapeInit(sb, target, node.Children, source + "." + nav.Name + "!", indent + 4);
                sb.AppendLine(",");
            }
        }

        sb.Append(pad).Append('}');
    }

    private void EmitQueryStruct(StringBuilder sb, FluentEntityModel m)
    {
        var entity = m.GlobalName;
        var concrete = Qualified(m, ConcreteName(m));
        var name = QueryName(m);

        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// A fluent, projection-first query. TShape is the interface view of the chain so");
        sb.AppendLine("/// far; only navigations included with With… are reachable on results. Results are");
        sb.AppendLine("/// never tracked.");
        sb.AppendLine("/// </summary>");
        sb.Append("internal readonly struct ").Append(name).AppendLine("<TShape>");
        sb.AppendLine("{");
        sb.Append("    internal readonly global::System.Linq.IQueryable<").Append(entity).AppendLine("> Source;");
        sb.Append("    internal readonly global::System.Linq.Expressions.Expression<global::System.Func<")
            .Append(entity).Append(", ").Append(concrete).AppendLine(">> Selector;");
        sb.AppendLine();
        sb.Append("    internal ").Append(name).Append("(global::System.Linq.IQueryable<").Append(entity)
            .Append("> source, global::System.Linq.Expressions.Expression<global::System.Func<")
            .Append(entity).Append(", ").Append(concrete).AppendLine(">> selector)");
        sb.AppendLine("    {");
        sb.AppendLine("        Source = source;");
        sb.AppendLine("        Selector = selector;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.Append("    private global::System.Linq.IQueryable<").Append(concrete).AppendLine("> Query");
        sb.AppendLine("        => global::System.Linq.Queryable.Select(global::Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.AsNoTracking(Source), Selector);");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Filters on the ENTITY, before projection — every mapped member is available here.</summary>");
        sb.Append("    public ").Append(name).Append("<TShape> Where(global::System.Linq.Expressions.Expression<global::System.Func<")
            .Append(entity).AppendLine(", bool>> predicate)");
        sb.AppendLine("        => new(global::System.Linq.Queryable.Where(Source, predicate), Selector);");
        sb.AppendLine();
        sb.AppendLine("    public string ToQueryString()");
        sb.AppendLine("        => global::Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToQueryString(Query);");
        sb.AppendLine();
        sb.AppendLine("    public async global::System.Threading.Tasks.Task<global::System.Collections.Generic.IReadOnlyList<TShape>> ToListAsync(global::System.Threading.CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        sb.AppendLine("        var rows = await global::Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync(Query, cancellationToken).ConfigureAwait(false);");
        sb.AppendLine("        // Zero-copy variance cast: every TShape is an interface the concrete shape implements.");
        sb.AppendLine("        return (global::System.Collections.Generic.IReadOnlyList<TShape>)(object)rows;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public async global::System.Threading.Tasks.Task<TShape?> FirstOrDefaultAsync(global::System.Threading.CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        sb.AppendLine("        var row = await global::Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstOrDefaultAsync(Query, cancellationToken).ConfigureAwait(false);");
        sb.AppendLine("        return (TShape?)(object?)row;");
        sb.AppendLine("    }");

        if (m.KeyMembers.Length > 0)
        {
            var parameters = string.Join(", ", m.KeyMembers.Select(k => k.TypeDisplay + " " + CamelCase(k.Name)));
            sb.AppendLine();
            sb.AppendLine("    /// <summary>Fetches by primary key — key members and order come from the EF model manifest.</summary>");
            sb.Append("    public async global::System.Threading.Tasks.Task<TShape?> GetByKeyAsync(")
                .Append(parameters).AppendLine(", global::System.Threading.CancellationToken cancellationToken = default)");
            sb.AppendLine("    {");
            sb.Append("        var filtered = global::System.Linq.Queryable.Where(Source, e => ");
            for (var i = 0; i < m.KeyMembers.Length; i++)
            {
                if (i > 0) sb.Append(" && ");
                var key = m.KeyMembers[i];
                sb.Append("global::Microsoft.EntityFrameworkCore.EF.Property<").Append(key.TypeDisplay)
                    .Append(">(e, \"").Append(key.Name).Append("\") == ").Append(CamelCase(key.Name));
            }

            sb.AppendLine(");");
            sb.AppendLine("        var row = await global::Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstOrDefaultAsync(global::System.Linq.Queryable.Select(global::Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.AsNoTracking(filtered), Selector), cancellationToken).ConfigureAwait(false);");
            sb.AppendLine("        return (TShape?)(object?)row;");
            sb.AppendLine("    }");
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static string CamelCase(string name)
    {
        if (name.Length == 0 || char.IsLower(name[0])) return "@" + name;
        var candidate = char.ToLowerInvariant(name[0]) + name.Substring(1);
        // A member like "Class" camel-cases into a reserved keyword; verbatim-escape those.
        return Microsoft.CodeAnalysis.CSharp.SyntaxFacts.GetKeywordKind(candidate) != Microsoft.CodeAnalysis.CSharp.SyntaxKind.None
            ? "@" + candidate
            : candidate;
    }

    private void EmitChains(StringBuilder sb, EntityPlan plan)
    {
        var m = plan.Model;
        var query = QueryName(m);

        sb.Append("internal static class ").AppendLine(ChainsName(m));
        sb.AppendLine("{");
        sb.Append("    /// <summary>Starts a fluent projection query for <see cref=\"").Append(m.GlobalName).AppendLine("\"/>.</summary>");
        sb.Append("    public static ").Append(query).Append('<').Append(InterfaceType(m, ImmutableArray<ChainNode>.Empty))
            .Append("> Facet").Append(m.SimpleName).AppendLine("(this global::Microsoft.EntityFrameworkCore.DbContext context)");
        sb.Append("        => new(context.Set<").Append(m.GlobalName).Append(">(), ")
            .Append(SelectorsName(m)).AppendLine(".Bare);");

        foreach (var edge in plan.Edges)
        {
            var fromState = plan.States[edge.FromCanon];
            var toState = EntityPlan.MergeInto(fromState, edge.Added);
            var nav = m.FindNav(edge.Added.Nav)!;

            sb.AppendLine();
            sb.Append("    public static ").Append(query).Append('<').Append(InterfaceType(m, toState))
                .Append("> With").Append(edge.Added.Nav).Append("(this ").Append(query).Append('<')
                .Append(InterfaceType(m, fromState)).Append("> query");
            if (edge.Added.Children.Length > 0)
            {
                var target = Target(nav);
                sb.Append(", global::System.Func<").Append(Qualified(target, MarkerName(target, ImmutableArray<ChainNode>.Empty)))
                    .Append(", ").Append(Qualified(target, MarkerName(target, ChainCanon.Sort(edge.Added.Children))))
                    .Append("> include");
            }

            sb.AppendLine(")");
            sb.Append("        => new(query.Source, ").Append(SelectorsName(m)).Append('.')
                .Append(SelectorProperty(toState)).AppendLine(");");
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    private void EmitMarkers(StringBuilder sb, EntityPlan plan)
    {
        var m = plan.Model;
        foreach (var state in plan.MarkerStates.OrderBy(s => s.Key, StringComparer.Ordinal))
        {
            var name = MarkerName(m, ChainCanon.Sort(state.Value));
            if (state.Key.Length == 0)
            {
                sb.AppendLine("/// <summary>");
                sb.AppendLine("/// Compile-time marker for nested includes. Never instantiated by user code and never");
                sb.AppendLine("/// invoked at runtime: the marker lambda only steers overload resolution by its return type.");
                sb.AppendLine("/// </summary>");
            }

            sb.Append("internal sealed class ").AppendLine(name);
            sb.AppendLine("{");
            sb.Append("    internal static readonly ").Append(name).AppendLine(" Instance = new();");
            sb.Append("    private ").Append(name).AppendLine("() { }");

            foreach (var edge in plan.MarkerEdges.Where(e => e.FromCanon == state.Key))
            {
                var toState = ChainCanon.Sort(EntityPlan.MergeInto(state.Value, edge.Added));
                var nav = m.FindNav(edge.Added.Nav)!;
                sb.AppendLine();
                sb.Append("    public ").Append(Qualified(m, MarkerName(m, toState))).Append(" With").Append(edge.Added.Nav).Append('(');
                if (edge.Added.Children.Length > 0)
                {
                    var target = Target(nav);
                    sb.Append("global::System.Func<").Append(Qualified(target, MarkerName(target, ImmutableArray<ChainNode>.Empty)))
                        .Append(", ").Append(Qualified(target, MarkerName(target, ChainCanon.Sort(edge.Added.Children))))
                        .Append("> include");
                }

                sb.Append(") => ").Append(Qualified(m, MarkerName(m, toState))).AppendLine(".Instance;");
            }

            sb.AppendLine("}");
            sb.AppendLine();
        }
    }
}
