// <auto-generated/>
#nullable enable

using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;

namespace InControl.Backend.Mapper;

public static partial class ContactDtoMapper
{
    /// <summary>
    /// Maps a <see cref="ContactEntity"/> instance to a new <see cref="ContactDto"/> instance.
    /// </summary>
    public static global::InControl.Common.Dto.MasterData.Contact.ContactDto ToContactDto(this global::InControl.Backend.Core.EntityFramework.Model.MasterData.Contact.ContactEntity source)
    {
        if (source == null) throw new ArgumentNullException(nameof(source));

        var target = new global::InControl.Common.Dto.MasterData.Contact.ContactDto();
        target.Address = source.Address;
        target.CultureInfo = source.CultureInfo;
        target.Description = source.Description;
        target.Email = source.Email;
        target.Name = source.Name;
        target.Number = source.Number;
        target.Phone = source.Phone;
        target.Type = source.Type;
        target.Url = source.Url;
        target.IsModifiedByIntegration = source.IsModifiedByIntegration;
        target.ModifiedByApplication = source.ModifiedByApplication;
        target.ModifiedByUnitId = source.ModifiedByUnitId;
        target.ModifiedByUserId = source.ModifiedByUserId;
        target.UpdateStatus = source.UpdateStatus;
        target.Id = source.Id;

        global::InControl.Backend.Mapper.ContactDtoMapConfig.Map(source, target);

        return target;
    }

    /// <summary>
    /// Maps a <see cref="ContactDto"/> instance back to a new <see cref="ContactEntity"/> instance.
    /// </summary>
    public static global::InControl.Backend.Core.EntityFramework.Model.MasterData.Contact.ContactEntity ToContactEntity(this global::InControl.Common.Dto.MasterData.Contact.ContactDto dto)
    {
        if (dto == null) throw new ArgumentNullException(nameof(dto));

        var target = new global::InControl.Backend.Core.EntityFramework.Model.MasterData.Contact.ContactEntity
        {
            Address = dto.Address,
            CultureInfo = dto.CultureInfo,
            Description = dto.Description,
            Email = dto.Email,
            Name = dto.Name,
            Number = dto.Number,
            Phone = dto.Phone,
            Type = dto.Type,
            Url = dto.Url
        };
        target.IsModifiedByIntegration = dto.IsModifiedByIntegration;
        target.ModifiedByApplication = dto.ModifiedByApplication;
        target.ModifiedByUnitId = dto.ModifiedByUnitId;
        target.ModifiedByUserId = dto.ModifiedByUserId;
        target.UpdateStatus = dto.UpdateStatus;
        target.Id = dto.Id;

        return target;
    }

    /// <summary>
    /// Applies the mapped properties of a <see cref="ContactDto"/> instance onto an existing
    /// <see cref="ContactEntity"/> instance in place.
    /// Properties excluded from this mapping are left unchanged on the source.
    /// </summary>
    /// <param name="dto">The DTO instance containing the values to apply.</param>
    /// <param name="source">The existing <see cref="ContactEntity"/> instance to update.</param>
    public static void ApplyToContactEntity(this global::InControl.Common.Dto.MasterData.Contact.ContactDto dto, global::InControl.Backend.Core.EntityFramework.Model.MasterData.Contact.ContactEntity source)
    {
        if (dto == null) throw new ArgumentNullException(nameof(dto));
        if (source == null) throw new ArgumentNullException(nameof(source));
        source.IsModifiedByIntegration = dto.IsModifiedByIntegration;
        source.ModifiedByApplication = dto.ModifiedByApplication;
        source.ModifiedByUnitId = dto.ModifiedByUnitId;
        source.ModifiedByUserId = dto.ModifiedByUserId;
        source.UpdateStatus = dto.UpdateStatus;
        source.Id = dto.Id;
    }

    /// <summary>
    /// LINQ projection expression for mapping <see cref="ContactEntity"/> to <see cref="ContactDto"/>.
    /// </summary>
    public static Expression<Func<global::InControl.Backend.Core.EntityFramework.Model.MasterData.Contact.ContactEntity, global::InControl.Common.Dto.MasterData.Contact.ContactDto>> ContactEntityToContactDtoProjection =>
        source => new global::InControl.Common.Dto.MasterData.Contact.ContactDto
        {
            Address = source.Address,
            CultureInfo = source.CultureInfo,
            Description = source.Description,
            Email = source.Email,
            Name = source.Name,
            Number = source.Number,
            Phone = source.Phone,
            Type = source.Type,
            Url = source.Url,
            IsModifiedByIntegration = source.IsModifiedByIntegration,
            ModifiedByApplication = source.ModifiedByApplication,
            ModifiedByUnitId = source.ModifiedByUnitId,
            ModifiedByUserId = source.ModifiedByUserId,
            UpdateStatus = source.UpdateStatus,
            Id = source.Id
        };
}
